### ISSUE TITLE
FeatureRequest: Paypal based charging

### ISSUE THREAD

**Issue by bash86** [snaptec/openWB#10]
Feature Request: Freischaltung der Wallbox mit Paypal. 
Der Preis pro kWh ist einstellbar: Beispiel 30Cent

-> An der Wallbox ist ein QR Code mit einem Bezahllink zu Paypal.
-> Der Nutzer will 10kWh nachladen, also bezahlt er mit Paypal 3€ im Voraus.
-> Nach 10kWh bricht die Wallbox den Ladevorgang ab, da die 3€ "verbraucht" wurden.

**Comment by snaptec** [comment]
aufgrund keiner nachfrage erstmal nicht.
