### ISSUE TITLE
aWATTar price chart shows UNIX-time on x-axis

### ISSUE THREAD

**Issue by olieske** [snaptec/openWB#1038]
time is still displayed as HH:MM  on my test installation 1.9.011a (2021-01-31 12:08:39 +0100 [a91651ca]
UNIX-time is  displayed on 1.9.012 (2021-02-10 08:34:53 +0100 [c6ab0b7f]

**Comment by MiOrt** [comment]
There is the old js-file in the cache... working on it

**Comment by MiOrt** [comment]
It seems that Safari for some reason is ignoring the reload mechanism by using query strings. I could solve the problem by emptying the cache and then completely shut down safari and restart again. What Browser are you on?

**Comment by olieske** [comment]
I'm running Firefox on Windows

Am 10.02.2021 um 17:35 schrieb Michael Ortenstein:

**Comment by MiOrt** [comment]
Strange... I never had this Problem before since we started using query strings. Could you please try to empty the browser Cache and reload the page again, maybe completely restart the browser?

**Comment by olieske** [comment]
cleaning the cache fixes the problem.

Am 10.02.2021 um 17:40 schrieb Michael Ortenstein:

**Comment by snaptec** [comment]
https://github.com/snaptec/openWB/pull/1039

Fixed
