### ISSUE TITLE
Command error in p1p3p.sh

### ISSUE THREAD

**Issue by Bucky2k** [snaptec/openWB#1045]
Maybe an issue only on my installation, but log shows:

u1p3p.sh: Zeile 49: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden. u1p3p.sh: Zeile 80: -: Kommando nicht gefunden.

**Comment by benderl** [comment]
#1046
