### ISSUE TITLE
Ladung geht bei weiter wenn man auf "Nur PV" wechselt.

### ISSUE THREAD

**Issue by radi334** [snaptec/openWB#108]
Hallo,

wenn ich in der OpenWB von "Jetzt Laden" auf "Nur PV" wechsele, dann wird bei 0 W auf PV die Ladung trotzdem mit dem vorherigen Wert forgesetzt.
Eigentlich müsste sich die LAdung doch stoppen in diesen Fall.

Gruß

Christoph

**Comment by snaptec** [comment]
Jein, hier wird wohl die Abschaltverzögerung noch mit im Spiel sein.
Wenn du (ladend) in den NurPV Modus wechselst, wird der Counter hier noch auf 0 sein.
Der zählt dann erst hoch und abgeschaltet wird wenn die Abschaltverzögerung erreicht ist.
