### ISSUE TITLE
Feature request: Ausgabe weiterer Werte aus ModBus Zähler

### ISSUE THREAD

**Issue by Roland-git** [snaptec/openWB#11]
Für die Freaks unter uns wäre es toll, wenn die openWB auch noch die Spannung und die Netzfrequenz im LAN und der Weboberfläche zur Verfügung stellen würde :)

**Comment by snaptec** [comment]
Das sollte als extra „expertenstatus“ webseite sein?
Für die hauptseite finde ich das etwas unrelevant. 
Den wert würde ich dann vom Ladeleistungszähler beziehen, Könnte man Pf und co auch gleich mitnehmen.

**Comment by Roland-git** [comment]
Da hast du recht...ist eher was für eine Extraseite.
Wäre klasse :)

**Comment by snaptec** [comment]
Für mich zur info:
EVSE DIN 1xxx Register mit ausgeben
