### ISSUE TITLE
Variable heißen kWh, meinen aber Wh

### ISSUE THREAD

**Issue by Flohlaus** [snaptec/openWB#1118]
![Bildschirmfoto 2021-03-03 um 20 57 32](https://user-images.githubusercontent.com/79670120/109885088-3f9e6200-7c7e-11eb-8e8f-7b9a8434a075.png)
Guten Abend,

es gibt zahlreiche Variable, die kWh heißen (einspeisungkwh, bezugkwh ...). Auch im Interface z. B. den allgemeinen EVU-Modulen http oder json wird die Eingabe für den Wert "kWh" verlangt und als Muster steht .kWh im Feld.
Der gesuchte Wert wird aber in Wh gerechnet, nicht in kWh.

Grundsätzlich sollte ein Wert nicht nach seiner Einheit benannt sein. Gesucht sind Leistung und Energiemenge, nicht W oder kWh.
Zumindest im User Interface sollte das richtig benannt sein (und lässt sich vermutlich auch schnell umsetzen).

**Comment by DetMoerk** [comment]
Ich verstehe den Hintergrund hinter dem Vorschlag, aber überleg mal, wenn jemand jetzt keinen oder wenig technischen Hintergrund hat, dann schaut er auf seinen Zähler oder auf die Webseite seines WR und findet dort eine Angabe kWh und eine Angabe in Watt. Was meinst du ist für diesen User einfacher zuzuordnen? Leistung und Energiemenge oder Watt und kWh.
Wobei man auch sagen muss, dass die spezifischen Module  den Kunden eh weiter an die Hand nehmen und das oft gar nicht verlangen. Bei den universellen http, json... ist oft schon mehr Detailwissen erforderlich.

Nur meine Meinung dazu.

VG
Det

**Comment by Flohlaus** [comment]
Das stimmt wohl. Aber wer ein json-Modul manuell nutzt muss mindestens die API vom Wechselrichter lesen. Und dann wäre ich erstmal irritiert, wenn die Eingabe in kWh verlangt wird, der WR aber Wh liefert.
Kann der Laie evtl. mit den Begriffen "Leistung [W]" und "Verbrauch [Wh]" was anfangen?

**Comment by Marcst76** [comment]
Schließe mich @Flohlaus an. Auch ich dachte nun erst, Mist, da muss ich noch Dinge umrechnen. Wenn "kWh" nur geschrieben ist, um "Verbrauch in Wh" zu  meinen, ist das ziemlich irritierend.

**Comment by Flohlaus** [comment]
Hier mal ein Vorschlag für die Benennungen. Ich denke es ist hilfreich, als Beispiel eine verschachtelte json Antwort zu nehmen, das wird der Standardfall sein, oder nicht?
![screenshot](https://user-images.githubusercontent.com/79670120/110307513-42db7a00-7fff-11eb-9d0f-02fc89fcd6d0.png)

**Comment by benderl** [comment]
In 1.9.225 behoben.
