### ISSUE TITLE
Logging Daten gekaufte OpenWB

### ISSUE THREAD

**Issue by Flohlaus** [snaptec/openWB#1119]
Guten Abend,

in meiner neu gekauften OpenWB Series2 Standard+ liegen irgendwelche alten Logging Files von 2018, 2020, usw... Die Files sind zwar größtenteils leer, aber das sieht etwas komisch aus.

Hilfreich wäre hingegen in dem Ordner eine Textdatei mit der Kopfzeile der Loggingdaten (Wenn es schon nicht in jede Logdatei direkt geschrieben werden kann). Dann muss man das nicht immer aus dem Forum raussuchen...

![Bildschirmfoto 2021-03-03 um 23 28 10](https://user-images.githubusercontent.com/79670120/109881258-46c27180-7c78-11eb-82b3-f0bbd26cc8e3.png)

**Comment by quasel** [comment]
gerade geguckt iss bei meiner gekauften auch so…

**Comment by benderl** [comment]
Da wurde vergessen das Image zu bereinigen. Die alten Logdateien stammen aus einem Entwicklungssystem und können gefahrlos gelöscht werden. Der Fehler wurde beim aktuellen Image, das auf die gekauften Boxen gespielt wird, behoben.
