### ISSUE TITLE
Integration SoC für Skoda

### ISSUE THREAD

**Issue by RalfAlbers** [snaptec/openWB#1139]
Integration eines Moduls zur Abfrage des SoC für Skoda Modelle.
Unter https://pypi.org/project/skodaconnect/ ist schon ein sehr gutes Python-Modul zu finden.

**Comment by Bucky2k** [comment]
Ich habe ein neues VAG Modul als Pull request eingestellt - es basiert auch auf EVCC und kann glaube ich auch Skoda. Einfach mal bei Fahrzeugtyp in kleinen buchstaben "skoda" eintragen

#1142

**Comment by Bucky2k** [comment]
@RalfAlbers Gern in  der aktuellen Nightly das VAG Modul testen - bisher habe ich nur VW prüfen können

**Comment by RalfAlbers** [comment]
ich lade mir morgen mal das Image und teste!

**Comment by Bucky2k** [comment]
Brauchst nur auf die aktuelle Nightly updaten

**Comment by mutsch75** [comment]
Kann ich bestätigen gleicher Fehler :

2021-03-19 07:04:28: Lp1: Error from evcc-soc: 2021/03/19 07:04:28 invalid vehicle type: skoda

**Comment by mutsch75** [comment]
Hab jetzt nicht im Detail nachgesehen aber laut Doku von EVCC werden nur die folgenden Modelle unterstützt "skoda: Skoda (Citygo, Enyaq)" also reine E-FAhrzeuge bei mir handelt es sich aber um einen SuperB iV (Plugin Hybrid)

**Comment by RalfAlbers** [comment]
ich habe einen Skoda Citigo-e IV

**Comment by mutsch75** [comment]
> ich habe einen Skoda Citigo-e IV

danit ist die Begründung dahin :-)

**Comment by Bucky2k** [comment]
Es liegt am nicht aktuellen EVCC Modul in der OpenWB - wir müssen uns noch gedulden

**Comment by benderl** [comment]
Mit EVCC (allgemeines Modul für alle implementierten Hersteller kommt in Kürze) und TRONITY stehen zwei Möglichkeiten bereit, den SoC abzufragen.
