### ISSUE TITLE
SOC ZeroNG - eingeschränkte Funktion?

### ISSUE THREAD

**Issue by Bucky2k** [snaptec/openWB#1143]
Wenn ich mich nicht täusche, funktioniert in diesem Modul das verkürzte Intervall nicht. Durch das logische OR wird immer das Standardintervall genutzt (glaube ich):

modules/soc_zerong/main.sh

```
if ( (( $ladeleistung > 800 )) && (( zerotimer < zintervallladen )) ) || (( zerotimer < zintervall )); then
	socDebugLog "Nothing to do yet. Incrementing timer."
	zerotimer=$((zerotimer+1))
	echo $zerotimer > $soctimerfile
else
	echo 0 > $soctimerfile
	socDebugLog "Requesting SoC"
...
```

**Comment by Bucky2k** [comment]
Wenn jemand diese Vermutung bestätigt, kann ich das gern korrigieren und ein Update vorschlagen

**Comment by benderl** [comment]
Die ersten beiden Vergleiche sind noch in einer Klammer zusammengefasst. Ich sehe da kein Problem.

**Comment by Bucky2k** [comment]
Ich hatte den Code für mein VAG/EVCC Modul kopiert und erst darüber die Fehlfunktion erkannt. In Worten besagt die If-Bedingung doch:
Wenn die Ladung aktiv ist und der Soc-Timer kleiner dem Lade-Aktualisierungsintervall ist ODER der Soc-Timer kleiner dem Standby-Aktualisierungsintervall ist, dann "Nothing to do/increment"

Letztere Bedingung ist immer true (da Ladeintdrvall < Standbyintervall) und damit immer vorrangig. Egal was die erste Abfrage ergibt.

Ich wäre echt baff wenn die Abfrage doch ihren Dienst erfüllt, dann habe ich echt einen Knoten im Kopf..

**Comment by benderl** [comment]
Sorry, hast Recht! Hatte nicht beachtet, dass dann nur der Timer hochgezählt wird. War gedanklich bei der Bedingung, dass die Abfrage gestartet wird.

**Comment by Bucky2k** [comment]
Die Variante im VAG Modul (PR) ist adaptiert vom Teslamodul - die läuft. Soll ich für das ZeroNG einen Bugfix vorschlagen?

**Comment by benderl** [comment]
Gerne als PR.
