### ISSUE TITLE
manuelles aktualisieren des SoC funktioniert nicht

### ISSUE THREAD

**Issue by RalfAlbers** [snaptec/openWB#1192]
Das manuelle aktualisieren des SoC funktioniert bei mir nicht.
Auf dem Main-Page habe ich bei dem Ladepunkt auf den aktualisieren Button unterhalb des SoC gedrückt.
![Zeichnung1](https://user-images.githubusercontent.com/44479345/111441946-224ea680-8708-11eb-90aa-4b5689027fb1.jpg)

**Comment by benderl** [comment]
Ist die Option "SoC nur Abfragen wenn Auto angesteckt" aktiviert? Falls ja, funktioniert das Aktualisieren auch nur, wenn das Fahrzeug angesteckt ist. Für weitere Untersuchungen fehlen alle wichtigen Daten wie z.B. die Versionsnummer, welche Hardware verwendet wird (Selbstinstallation oder gekaufte openWB) etc. Wenn es eine gekaufte openWB ist, dann bitte in den Einstellungen einen Fehlerberich absenden. Bei Selbstinstallationen bitte im Forum nachfragen: [https://openwb.de/forum/](url)
