### ISSUE TITLE
temporäres Sofortladen per (Hardware)Taster

### ISSUE THREAD

**Issue by e-lmo** [snaptec/openWB#12]
Sofortladen über Taster an der Wallbox wie bisher. 
Nach Ende der Ladung (Ladeleistung=0) Rückfall auf vorigen Lademodus -als Voreinstellung für die nächste Ladung.

**Comment by snaptec** [comment]
Der Lademodus ist global umstellbar.
Hierzu muss ein Taster gegen folgende GPIOs gelegt werden:

         button1_state = GPIO.input(12)
         button2_state = GPIO.input(16)
         button3_state = GPIO.input(6)
         button4_state = GPIO.input(13)

button 1 = Sofort Laden
button 2 = Min + PV Laden
button 3 = Nur PV Laden
button 4 = Stop

Ladeleistung Rückfall auf 0 ist leider nicht so einfach aufgrund der mehreren Ladepunkte und der Abhängigkeiten.
