### ISSUE TITLE
EVU Modul Powerfox

### ISSUE THREAD

**Issue by mutsch75** [snaptec/openWB#1205]
Ich hab ein kleines EVU Modul für Powerfox geschrieben
Bin jetzt noch nicht so versiert mit GIT wie soll ich euch die Dateien zukommen lassen ?

**Comment by benderl** [comment]
Am Besten hier per PullRequest.

**Comment by mutsch75** [comment]
Bin wahrscheinlich zu blöde aber entweder ich mach was falsch oder ich habe keine Berechtigung

**Comment by CONSULitAS** [comment]
Versuch mal das: https://www.nexmo.com/legacy-blog/2020/10/01/how-to-create-a-pull-request-with-github-desktop
