### ISSUE TITLE
optionale Zugangssicherung der Weboberfläche

### ISSUE THREAD

**Issue by tomac01** [snaptec/openWB#1209]
Hallo,

ich würde gerne meine Weboberfläche der OpenWB über das Internet erreichbar machen. Damit aber nicht jeder meine Daten und Ladeeinstellungen einsehen und verändern kann, bräuchte ich eine optionale Möglichkeit einer Zugangssicherung (Anmeldung per Login) um den Zugriff auf die Weboberfläche abzusichern.
Zusätzlich müsste ein verschlüsselter Zugriff über https ermöglicht werden.

Die bisherige Absicherung nur zum Aufruf der Einstellung ist dafür nicht ausreichend.

Vielen Dank!

**Comment by benderl** [comment]
Nutz dazu bitte die Cloud. Es wird dringend davon abgeraten, einen externen Zugriff direkt auf die openWB (z.B. durch Portfreigabe im Router) einzurichten. Du kannst Dein Vorhaben aber mit entsprechenden Kenntnissen mit einem Reverse Proxy umsetzen. Dort können dann alle Daten zu Https und Anmeldung eingerichtet werden.
