### ISSUE TITLE
Modules for Outlander PHEV, SMA Tripower 5.0 and SMA Sunny Island 6.0

### ISSUE THREAD

**Issue by roesl** [snaptec/openWB#122]
HI,

does anybody have modules for my devices or are existing modules compatible with my devices ?

regards
Georg

**Comment by david-m-m** [comment]
The modbus protocol for all SMA tripower inverters is identical. You can safely use the tri900 module currently provided.

**Comment by david-m-m** [comment]
Without having researched it: I'd think that the modbus protocol for Sunny Boy Storage and Sunny Island should also be identical. (At least the SBS module is using the standardized set of registers...)

**Comment by snaptec** [comment]
Tripower can be used with die SMA WR Modul.
Sunny Island is integrated as modul in beta 1.49. They use slightly different registers.
Is there a api for the Outlander?
regards

**Comment by snaptec** [comment]
As of no reaction
