### ISSUE TITLE
Audi etron SOC still not usable

### ISSUE THREAD

**Issue by JanTTTTT** [snaptec/openWB#1232]
The necessary function to pull the etron (55) SOC from VAG/Audi´s servern is still not working. If activated the log allways shows "unvalid password" (and lots of other stuff which dosend make sense). For a smart energy management the SOC is mandatory (e.g. night charging, Awattar, etc.). No idea what the problem is in OpenWB but other platforms (eg Tronity.io) are able to pull those data w/o any problem from the auto servers (several OEMs). Maybe an interface to this plaform might be the best way to get rid of permanent changes on the auto OEM side... tronity might take care. BTW. also ABRP integrated this interface in their software...

**Comment by andig** [comment]
Same root cause as https://github.com/snaptec/openWB/issues/1139#issuecomment-802685447
