### ISSUE TITLE
Fehlender PV Wert in Monatsansicht zum Logging/Graph

### ISSUE THREAD

**Issue by tomac01** [snaptec/openWB#1233]
In der Monatsansicht fehlt der PV-Wert.
Inder Tages- und Jahresansicht ist dieser enthalten.

installierte Version: 1.9.225 (2021-03-24 19:34:42 +0100 [d66b5902] )

![14FB7443-90DD-475D-92B6-9D0874EEA454](https://user-images.githubusercontent.com/26430993/112387623-4c98f900-8cf2-11eb-93e4-4c9d1ea77bda.png)

**Comment by benderl** [comment]
Das ist ein individuelles Problem. Bitte im Forum klären oder, falls es eine fertig gekaufte openWB ist, mit einem Fehlerbericht an den Support wenden.
