### ISSUE TITLE
Kann ich die Sonnenbatterie 10 integrieren

### ISSUE THREAD

**Issue by miwi-1209** [snaptec/openWB#1256]

**Comment by DetMoerk** [comment]
Ich denke die Frage ist im Forum besser aufgehoben als hier.

https://openwb.de/forum/index.php

Aber am besten erst mal mir einer Suche beginnen im Forum. 

VG
Det

**Comment by benderl** [comment]
Hat sich gegenüber der Version 8 die API geändert?
Ruf mal im Browser folgende URL auf: `<IP-der-Sonnenbatterie>/api/v1/status`

**Comment by ginan2** [comment]
Hallo,

bei mir funktioniert es als Sonnen Eco Batterie:

In den EVU Einstellungen:
![image](https://user-images.githubusercontent.com/82163790/114044001-17121500-9887-11eb-90c2-7404bd9f7424.png)

Unter Batteriespeicher Einstellung:
![image](https://user-images.githubusercontent.com/82163790/114043760-ddd9a500-9886-11eb-906f-45a96f5c4441.png)

LG

ginan2

**Comment by benderl** [comment]
Damit sollte die Frage beantwortet sein.
