### ISSUE TITLE
Debug Logeintrag

### ISSUE THREAD

**Issue by Bucky2k** [snaptec/openWB#1291]
Was steht hinter folgendem Logeintrag für eine Ursache? Ist kürzlich nach Update (Nightly) aufgetreten:

`ValueError: invalid option string 'a': must start with a character '-' raise ValueError(msg % tup) File "/usr/lib/python2.7/argparse.py", line 1410, in _get_optional_kwargs kwargs = self._get_optional_kwargs(*args, **kwargs) File "/usr/lib/python2.7/argparse.py", line 1280, in add_argument parser.add_argument("a", "address", type=str, help="ip address") File "runs/u1p3premote.py", line 9, in <module> Traceback (most recent call last): 2021-04-09 05:01:17: Pause nach Umschaltung: 2s (LV0)`

**Comment by benderl** [comment]
Sollte mit #1293 behoben sein.
