### ISSUE TITLE
Sonderzeichen Passwort ( VAG, ID, Audi, EVCC Modul)

### ISSUE THREAD

**Issue by Bucky2k** [snaptec/openWB#1299]
In den EVCC basierten Modulen wird die EVCC-binary wie folgt aufgerufen:

answer=$($MODULEDIR/../evcc-soc-abo $fztype --user "$username" --password "$password" --vin "$vin" --token "$token" 2>&1)

Durch die Shell-Interpretation werden Sonderzeichen aber falsch interpretiert unter z.B. --password "$password", richtig?

Ein einfaches Ersetzen der " gegen ' (bei allen Variablen) auf Empfehlung von AndiG (EVCC) hat ad-hoc nicht funktioniert. Kann mir wer sagen, wie das Problem bzw. die Einschränkung umgangen werden kann? Z.B. verlangt Porsche ein Sonderzeichen im Passwort - gehen da alle Sonderzeichen?

**Comment by benderl** [comment]
Zumindest bei dem etwas älteren Python argparse Modul gibt es einen Bug. Um Sonderzeichen komplett an den Prozess zu übergeben, muss die Syntax `... --param='value'` benutzt werden. Wie das in Go aussieht, kann ich nicht beurteilen. Da kann aber sicher AndiG etwas zu sagen. Singlequotes sind bei Kennwörtern zwingend erforderlich.

**Comment by andig** [comment]
> Zumindest bei dem etwas älteren Python argparse Modul gibt es einen Bug. Um Sonderzeichen komplett an den Prozess zu übergeben, muss die Syntax `... --param='value'` benutzt werden. Wie das in Go aussieht, kann ich nicht beurteilen. Da kann aber sicher AndiG etwas zu sagen. Singlequotes sind bei Kennwörtern zwingend erforderlich.

Parsen tut m.e. die Shell und nicht Go. Dort wird nur noch argv übergeben.

**Comment by Bucky2k** [comment]
Wie gesagt, ich kenne generell die Syntax hier nicht, ich habe nur aus anderen Modulen übernommen. Ändere ich:

`answer=$($MODULEDIR/../evcc-soc-abo $fztype --user "$username" --password "$password" --vin "$vin" --token "$token" 2>&1)`

in

`answer=$($MODULEDIR/../evcc-soc-abo $fztype --user "$username" --password '$password' --vin "$vin" --token "$token" 2>&1)`

bekomme ich Fehler aus dem EVCC Modul zurück. Ich belasse es erstmal bei den double-quotes, schlicht weil mir der Ansatz fehlt wie das robuster gemacht werden kann. Bucky

**Comment by benderl** [comment]
Eventuell wird es mit #1306 behoben.

**Comment by benderl** [comment]
> Wie gesagt, ich kenne generell die Syntax hier nicht, ich habe nur aus anderen Modulen übernommen. Ändere ich:
> 
> `answer=$($MODULEDIR/../evcc-soc-abo $fztype --user "$username" --password "$password" --vin "$vin" --token "$token" 2>&1)`
> 
> in
> 
> `answer=$($MODULEDIR/../evcc-soc-abo $fztype --user "$username" --password '$password' --vin "$vin" --token "$token" 2>&1)`
> 
> bekomme ich Fehler aus dem EVCC Modul zurück. Ich belasse es erstmal bei den double-quotes, schlicht weil mir der Ansatz fehlt wie das robuster gemacht werden kann. Bucky

Mit den Singlequotes unterbindest Du jegliche Variablenexpansion. Dem evcc wird dann buchstäblich $password übergeben.

**Comment by benderl** [comment]
Nach dem PR #1325 sollte es eigentlich funktionieren. Bitte testen.

**Comment by benderl** [comment]
Wie sieht es aus? Abgesehen von ' sollte es mit allen Sonderzeichen funktionieren. Könnt ihr das bestätigen?

**Comment by Bucky2k** [comment]
Müsste es schon einfach so funktionieren oder muss im Modul im Aufruf noch
von " auf ' beim PW gewechselt werden?

benderl ***@***.***> schrieb am Sa., 24. Apr. 2021, 10:53:

**Comment by benderl** [comment]
Nein, ansonsten übergibst Du wieder $password an evcc, ohne Variablenexpansion.

**Comment by Bucky2k** [comment]
Soeben ein Passwort mit Ziffern, Groß/Kleinschreibung und #, ! und & angelegt und erfolgreich den SOC abrufen können. Ich würde sagen läuft

**Comment by benderl** [comment]
Dann schließe ich mal ab.
