### ISSUE TITLE
Software-Schalter zur Anpassung des Regelbereiches Solarladen

### ISSUE THREAD

**Issue by e-lmo** [snaptec/openWB#13]
Bisher erfolgt die Regelung für Solarladen im Bereich der Einspeiseleistung 0-230W (einphasig)
Über den Schalter erfolgt die Auswahl, ob dieser Regelbereich wie bisher oder im Bereich von 0-230W Bezug erfolgen soll. 
Vorschlag zur Benennung: 
Regelziel: Vermeidung von Einspeisung oder Bezug.

**Comment by snaptec** [comment]
In version 0.4 hinzugefuegt.
Die Regelung erfolgt pro Phase, die Phasigkeit wird automatisch erkannt.
