### ISSUE TITLE
Mindestüberschuss und Abschaltschwelle wird falsch berechnet

### ISSUE THREAD

**Issue by tammof** [snaptec/openWB#131]
Version 1.42
Mir scheint der Wert Mindestüberschuss aus den PV Ladeeinstellungen wird falsch berücksichtigt. Bei einem dreiphasigen Anschluss der go-e erscheint bei einem Eintrag von 
Mindestüberschuss: 4000 W
Folgender Eintrag im Log:
```
uberschuss 5705 wattbezug -5705 ladestatus 0 llsoll 0 pvwatt -6017 mindestuberschussphasen **12000** wattkombiniert 5705 abschaltungw 1560 schaltschwelle 690
Fri 19 Apr 13:20:45 CEST 2019
```
Die Ladung startet nicht, da "mindestuberschussphase 12000" obwohl 5705 W Überschuss vorhanden sind.

Bei einem Eintrag von 
Mindestüberschuss: 1333 W
erscheint dann korrekterweise:

```
uberschuss 5729 wattbezug -5729 ladestatus 0 llsoll 0 pvwatt -6013 mindestuberschussphasen **3999** wattkombiniert 5729 abschaltungw 1560 schaltschwelle 690
Fri 19 Apr 13:20:55 CEST 2019
```
und die Ladung beginnt.
Nachdem die Ladung beginnt scheint der Wert "1333" dann korrekt übernommen zu werden:

```
Fri 19 Apr 13:21:51 CEST 2019
uberschuss 5757 wattbezug -5757 ladestatus 1 llsoll 6 pvwatt -6061 mindestuberschussphasen 1333 wattkombiniert 5757 abschaltungw 520 schaltschwelle 230
```

Gleiches gilt für "schaltschwelle":

```
Fri 19 Apr 13:22:15 CEST 2019
uberschuss 3270 wattbezug -3270 ladestatus 1 llsoll 6 pvwatt -6063 mindestuberschussphasen 1333 wattkombiniert 4590 abschaltungw 520 schaltschwelle 230
Fri 19 Apr 13:22:25 CEST 2019
uberschuss 225 wattbezug -225 ladestatus 1 llsoll 8 pvwatt -6064 mindestuberschussphasen 3999 wattkombiniert 5925 abschaltungw 1560 schaltschwelle 690

```

**Comment by snaptec** [comment]
Absolut korrekt so. 
Die Werte werden immer für einphasiges Laden angegeben. 
OpenWB erkennt mit wieviele Phasen geladen wird und rechnet dann um. 
Ich ergänze den Hinweis in der Einstellungsseite.

**Comment by tammof** [comment]
Gut zu wissen, danke!
