### ISSUE TITLE
Fehler bei CP-Unterbrechung in nurpv.sh

### ISSUE THREAD

**Issue by miradarya** [snaptec/openWB#1312]
Seit #1289 stimmt in https://github.com/snaptec/openWB/blob/132383083fb5ebdb58b0fae2736c1d0b82e49bba/nurpv.sh#L185 was nicht:
`nurpv.sh: Zeile 185: 0: Kommando nicht gefunden.`
@MartinRinas

**Comment by MartinRinas** [comment]
ack, schau' ich mir heute Abend an was da los ist.

**Comment by MartinRinas** [comment]
ist in https://github.com/snaptec/openWB/pull/1315 gefixt, tippfehler in der schleife @miradarya
