### ISSUE TITLE
PSA-SOC UnicodeEncodeError

### ISSUE THREAD

**Issue by 0815simon** [snaptec/openWB#1397]
Fehler beim Abrufen der SOC beim PSA-Modul (bei mir Citroen): 

Traceback (most recent call last):
  File "/var/www/html/openWB/modules/soc_psa/psasoc.py", line 92, in <module>
    f.write(str(responsetext))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 435: ordinal not in range(128)

Sobald responsetext Zeichen außerhalb des ascii-Satzes (UTF8) enthält gibt es die o.g. Fehlermeldung.

**Comment by benderl** [comment]
Sollte jetzt in der Nightly behoben sein.

**Comment by 0815simon** [comment]
Bestätige dass es jetzt behoben ist.
