### ISSUE TITLE
Reduzierter Ladestrom Min für Lastmanagement

### ISSUE THREAD

**Issue by e-lmo** [snaptec/openWB#14]
Aus Gründen der Effizienz möchte ich einen Ladestrom unterhalb von 9A z.B. beim PV-laden möglichst vermeiden.
Für das Lastmanagement würde ich auch den Ladestrom bis 6A herunter freigeben wollen.
Also mein Wunsch: neben dem normalen Mindestladestrom einen "reduzierten Mindestladestrom für Lastmanagement" einführen, auf den lediglich das Lastmanagement reduzieren darf. 
Alternativ für das Lastmanagement unabhängig vom eingestellten Mindestladestrom bis 6A  herunteregeln lassen, wie es der Ladestandard auch vorsieht.

**Comment by snaptec** [comment]
ist bereits implementiert
