### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by IngmarStein** [snaptec/openWB#1411]
Currently, builds are released by bumping the version in https://github.com/snaptec/openWB/blob/master/web/version. Releases are designated as beta or stable by merging them into the respective branches.

This makes it hard to build a given version from source. For example, to build 1.9.220, one would need to find the commit which bumped the version number to that string and build from that commit. This makes it infeasible to provide Docker images corresponding to specific OpenWB releases.

Would you consider tagging releases with git tags?

**Comment by benderl** [comment]
We will switch to regular releases with version 2.0.

**Comment by ChrisMuki** [comment]
Using releases or tags instead of that version file would also make the whole project feel more mature 😉
