### ISSUE TITLE
Support dynamic evcc vehicles selection

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#1438]
See 

```
❯ curl https://cloud.evcc.io/api/vehicles
[{"id":"audi","name":"Audi"},{"id":"bmw","name":"BMW"},{"id":"citroen","name":"Citroën"},{"id":"default","name":"Default"},{"id":"ford","name":"Ford"},{"id":"hyundai","name":"Hyundai"},{"id":"kia","name":"Kia"},{"id":"nissan","name":"Nissan"},{"id":"carwings","name":"Nissan (Leaf pre 2019)"},{"id":"opel","name":"Opel"},{"id":"ovms","name":"Ovms"},{"id":"peugeot","name":"Peugeot"},{"id":"porsche","name":"Porsche"},{"id":"renault","name":"Renault"},{"id":"seat","name":"Seat"},{"id":"vw","name":"VW"},{"id":"id","name":"VW ID"},{"id":"volvo","name":"Volvo"},{"id":"skoda","name":"Škoda"},{"id":"enyaq","name":"Škoda Enyaq"}]
```

**Comment by benderl** [comment]
@Bucky2k 
Willst Du das noch umsetzen?

**Comment by Bucky2k** [comment]
Grundsätzlich ja, aber noch ist ja kein Bedarf entstanden. Die Statische Liste ist meines Wissens nach noch vollständig. Vielleicht habe ich nächste Woche etwas Luft und Langeweile

**Comment by andig** [comment]
Ich glaube aktuell fehlt noch Carwings in der Auswahl für die alten Leaf. Ist aber sicher kein Massenphänomen.

**Comment by andig** [comment]
EVCC hat in master jetzt auch Unterstützung für den Fiat500e. Per Cloud könnte ich das sofort verfügbar machen- würde aber davon abhängen, die Liste zu erweitern oder zu dynamisieren. Könntet ihr Euch das nochmal anschauen? Vielen Dank!!!

**Comment by Bucky2k** [comment]
Mangels Zeit erstmal nur das Dropdown erweitert: #1496

@andig: "fiat" als Übergabestring für den Fahrzeugtyp ist korrekt?

**Comment by andig** [comment]
Super, danke 🙏

**Comment by andig** [comment]
Ich schaue mal ob ich die dynamische Auswahl per copy/paste hinbekomme. Nur testen kann ichs mangels owb leider nicht.

**Comment by Bucky2k** [comment]
Sende mir den vorbereiteten Codeschnipsel gern zu - testen bekomme ich bestimmt noch unter

**Comment by andig** [comment]
Ich hab mir das angeschaut, aber blicke nicht durch. Die jquery Hölle in einer 5000 Zeilen langen Datei ist nicht meins. Muss also fürs Erste bleiben wie es ist :(

**Comment by ts78** [comment]
Ich habe die API Abfrage eingefügt, getestet und als Pull Request gestellt.

**Comment by andig** [comment]
Top, vielen Dank @ts78 !!!

**Comment by ts78** [comment]
@andig: Für den Nutzer wäre es im Übrigen übersichtlicher, wenn Škoda nach Seat und vor VW kommt - hast du Einfluss auf die Reihenfolge der Items?

**Comment by andig** [comment]
Nur wenn ich die Liste con Hand baue. Es scheint kein entsprechendes Unicode Sort zu geben in Go :(

**Comment by andig** [comment]
Nvm. Natürlich gibts das. Ändere ich asap…

**Comment by ts78** [comment]
:+1:

**Comment by andig** [comment]
Ist drin, danke für den Hinweis. Ich mag mal wieder wie einfach das in Go ist:

	collator := collate.New(language.Make("de"))

	sort.Slice(types, func(i, j int) bool {
		return collator.CompareString(types[i].Name, types[j].Name) < 0
	})

Einfach aus `strings.Compare` ein `collator.Compare` gemacht.
