### ISSUE TITLE
Feature Request: Überschussabhängige Steuerung weiterer Verbraucher

### ISSUE THREAD

**Issue by e-lmo** [snaptec/openWB#15]
Eine Überschussabhängige Steuerung weiterer Verbraucher könnte durchaus eine sinnvolle Ergänzung zur solargeführten Überschussladung sein.  
Gerade kleinere Verbraucher(<1kW), deren Betrieb sich problemlos verschieben lässt, könnten die Lücke füllen, die der Mindestladestrom von 6A bedingt, bzw. den Solarstrom verbrauchen, sofern kein Fahrzeug zur Ladung bereitsteht.

Beispiel Poolpumpe: Leistung ca. 600W. Priorität eine Stufe geringer als die Fahrzeugladung.
Der Einsatzzeitraum lässt sich problemlos verschieben.  Es muss lediglich gewährleistet werden, dass diese eine festzulegende Mindestlaufzeit von z.B. 5h/d erreicht. Restlaufzeit könnte während des Nacht-Ladezeitraums nachgeholt werden. Idealerweise nach Beendigung der Ladung durch das Fahrzeug. 
Aktuell wird die Pumpe durch eine Zeitschaltuhr mit festen Zeiten gesteuert und das Ladeschütz schaltet die Poolpumpe aus, da ich während der Fahrzeug-Ladung kein Überschuss erwarte.

Beispiel Brunnenpumpe:
Ich fülle die Regenwassertanks bei dem aktuell trockenen Wetter mithilfe einer Brunnenpumpe nach. Diese läuft mit ca 500W aktuell mehrere Stunden pro Tag und wird durch einen Schwimmerschalter und Zeitschaltuhr tagsüber gefüllt.  Ein nächtliches Nachholen erscheint mir hier nicht sinnvoll, sonst sind die Tanks morgens schon voll. Wasser wird eher am Nachmittag benötigt.

Weitere verschiebbare Verbraucher:
Rasenmäher-Akku ca. 200W Ladezeit ca 1,5h. Niedrigste Priorität. Ladegerät lädt mit gestecktem Akku sofort nach Einstecken des Schuko-Steckers.

Schon ein GPIO-Ausgang der bei einem Überschuss von z.B. 500W einschaltet und einem Bezug von z.B. 100W bzw. Beim Start der Fahrzeugladung ausschaltet, bietet einen einfachen und praktischen Mehrwert zur PV-Nutzung über die reine Fahrzeugladung hinaus.

**Comment by snaptec** [comment]
Sehr gute Ideen. 
Dies wird durch einen übergeordneten Energiemanager realisiert. 
OpenWB ist dann ein Client davon mit einstellbarer Priorität. 

Ist in der mache, dauert noch etwas.
