### ISSUE TITLE
screenshots4wiki

### ISSUE THREAD

**Issue by m4ding** [snaptec/openWB#1500]
man kann sonst nirgendswo bilder im wiki hoch laden f![mqtt](https://user-images.githubusercontent.com/65028008/127337306-d62b2847-80c9-4d1a-9e99-ef83592beb79.PNG)
![mqtt_config1](https://user-images.githubusercontent.com/65028008/127337538-fd29e03c-bf7e-4c1d-b5ae-76b055f0efd1.PNG)
![mqtt_config2](https://user-images.githubusercontent.com/65028008/127337544-162c1f94-17ab-4b37-808d-9836bcdd130d.PNG)
r Artikel...

**Comment by m4ding** [comment]
![mqtt_objekte](https://user-images.githubusercontent.com/65028008/127338180-32b3c145-fc96-4f8b-ab21-ff361e56ecb3.PNG)

**Comment by JSAnyone** [comment]
Du musst das Issue nicht abschicken. Reicht wenn du die Bilder hochlädst, dann den Link von den Bildern kopierst und das Issue verwirfst.

**Comment by m4ding** [comment]
sehr gut, danke!
