### ISSUE TITLE
Soc von Tesla wird nicht aktualisiert 

### ISSUE THREAD

**Issue by soso1999** [snaptec/openWB#1516]
Soc wird automatisch nicht aktualisiert, egal wie viele Minuten ich einstelle. Ich muss immer auf den Aktualisierungs-Button damit es funktioniert! OpenWB wird mit TMCManager benutzt.

**Comment by benderl** [comment]
Ohne weitere Angaben ist es unmöglich, das zu untersuchen. Am Besten im Forum dazu einen Beitrag schreiben mit allen Angaben zur Installation.
