### ISSUE TITLE
Tesla SOC: Login wg. Re-Captcha nicht mehr möglich

### ISSUE THREAD

**Issue by riesi77** [snaptec/openWB#1587]
Die Loginfunktion im Tesla SOC funktioniert nicht mehr, seit Tesla auf Re-Captcha umgestellt hat.
Es kommt die Fehlermeldung: "It's looks, that the Captca is wrong".
Auswirkung: SOC kann nicht mehr ausgelesen werden.

**Comment by benderl** [comment]
Die SoC Module werden teilweise von der Community gepflegt. Am Besten im Forum unter SoC nachsehen.
Das Problem mit dem Tesla Modul ist bereits bekannt, konnte jedoch mangels Zeit noch nicht behoben werden.

**Comment by riesi77** [comment]
Das ist jetzt für mich kein Grund, den Bug zu schließen.
