### ISSUE TITLE
Integration ModBus Meter MPM3PM

### ISSUE THREAD

**Issue by gb1973** [snaptec/openWB#16]
Wer hat Interesse den ModBus Zähler MPM3PM von Bernecker Austria zu integrieren.
Der Zähler ist von uns entwickelt (ich bin ehemaliger Fronius Entwickler) und hat idente Register wie ABB Zähler und wird bereits bei Loxone und und Siemens Logo verwendet.
Der Zähler funktioniert natürlich auch über ModBus TCP <-> RTU koppler.
Man müsste nur die Registerdefinition von MP630 anpassen.
[MPM3PModBus.pdf](https://github.com/snaptec/openWB/files/2240380/MPM3PModBus.pdf)

**Comment by snaptec** [comment]
Zähler sehen gut aus!
Kann ich gerne implementieren. 
Dafür bräuchte am besten ein Demo Exemplar hier.

**Comment by gb1973** [comment]
Das sollte kein Problem sein, kann ich gerne Muster senden :)

**Comment by snaptec** [comment]
Sehr schön.
Rest am besten per mail:
info@snaptec.org

**Comment by gb1973** [comment]
(mail)

**Comment by snaptec** [comment]
als beta für Ladepunkt 1 integriert.
Bitte testen und Feedback geben. 
Wird dann für die anderen Ladepunkte sowie EVU nachtgetragen.

**Comment by snaptec** [comment]
Update:
Warte hier noch auf Feedback ...

**Comment by snaptec** [comment]
eingebaut mit v0.93
