### ISSUE TITLE
NurPV: OpenWB flappt bei 16A max. zwischen 1 und 3 Phasen

### ISSUE THREAD

**Issue by gvzdus** [snaptec/openWB#1623]
Grundsatz:
- Das typische Setup ist ja 6-16 A je Phase, oder 6-32 A je Phase. Wobei die "KfWler" eben auf 16 A max. fahren müssen.
- Bei 16 A max. liegt ein substanzieller Regelabstand zwischen 1P und 3P: 1P ist 1,4 - 3,7 kW, 3P ist 4,1 kW bis 11 kW
- Bei 32 A max. überlappen sich die Regelbereiche: 1P ist 1,4 - 7,4 kW, 3P ist 4,1 kW bis 22 kW

Nun scheint mir in der u1p3p.sh diese Nicht-Überlappung der Phasenbereiche, also die 16A-Konfiguration, zumindest beim Überschussladen (2) nicht berücksichtigt: In Zeile 257 ff. der u1p3p.sh wird der Fall "Gehe ich von 1P auf 3P behandelt?". In Zeile 274

if (( oldll == maximalstromstaerke )); then
steht m.E. das einzige Kriterium für das Hochgehen auf 3P (bzw. den Timer hochzuzählen): Die Maximalstromstärke 1P ist erreicht.
Der selbe Flaw befindet sich in Gegenrichtung: Ab Zeile 296 ff. befindet sich das Handling "Will ich runter von 3P auf 1P?".
Hier ist das Kriterium in Zeile 309:

if (( oldll == minimalapv )); then
Für 16A-Boxen wird daher m.E. im Überschussbereich von 3,7 kW bis 4,8 kW ein permanenter (also: 8-minütiger) Wechsel zwischen 1- und 3-P getriggert: Bei P1/16A wird für den Wechsel auf 3P gezählt, ohne zu prüfen, ob denn 4,1 kW Überschuss da wären. Und anders herum wird bei 4,1-4,8 kW Überschuss - also wenn mit P3/6A geladen wird, völlig sinnlos ein Wechsel in den 1P-Modus "angezählt" - obwohl man gerade im 3P-Laden prima aufgehoben ist.

**Comment by simonihmig** [comment]
Ja, das nervt mich auch schon länger. Kommt bei meiner Auslegung der PV-Anlage durchaus sehr häufig vor. Folgender Screenshot zeigt die vielen unnötigen Umschalt-Vorgänge:

![Bildschirmfoto 2021-09-22 um 16 03 10](https://user-images.githubusercontent.com/1325249/159173724-6eecc434-f237-404c-869d-80fa6989a362.png)

**Comment by apfelschorle74** [comment]
Hier genau das Gleiche. Kriterium für 1P->3P sollte der zur Verfügung stehende Mehr-Überschuss sein.

**Comment by dergreg** [comment]
Hab gerade kein Auto zum Testen da, das dürfte bei meiner PV-Auslegung aber auch öfter vorkommen.

Sollte es nicht reichen die Bedingung wie folgt anzupassen?

`if ((oldll == maximalstromstaerke) && (uberschuss >= (3 * 230 * minimalstromstaerke))`

und für von 3p auf 1p

`if ((oldll == minimalapv)) && (uberschuss <= (3 * 230 * minimalapv)`

**Comment by benderl** [comment]
An der Regelung in der 1.9er Version werden keine Änderungen mehr vorgenommen. In der Vergangenheit haben sich bereits solche auf den ersten Blick überschaubaren Anpassungen als sehr problematisch herausgestellt.

Die 2.0 steht bereits in den Startlöchern und hat keine Probleme mit diesem "Gap" bei der Umschaltung.

**Comment by apfelschorle74** [comment]
@benderl Interessante Argumentation: Erst das Problem zweieinhalb Jahre liegen lassen und dann auf 2.0 verweisen, die mindestens ebenso lange schon in der Mache ist und zum Zeitpunkt dieser Problemmeldung gerade mal Alpha-Status hatte. Finde ich ein bisschen enttäuschend.
