### ISSUE TITLE
Unterstützung Solarmax Speicher

### ISSUE THREAD

**Issue by mobbl** [snaptec/openWB#1631]
Gibt es eine Möglichkeit die Speicherlösung von Solarmax abzufragen?

https://www.solarmax.com/de/solarmax-tp-s-serie/

**Comment by benderl** [comment]
Gibt es hierzu eine Dokumentation? Die Wechselrichter können inzwischen eingebunden werden.

**Comment by Maxify23** [comment]
Ich glaube ich habe da was gefunden. 

[MAX.STORAGE_ModbusTCP_Datenpunktliste-1.pdf](https://github.com/snaptec/openWB/files/11486863/MAX.STORAGE_ModbusTCP_Datenpunktliste-1.pdf)
