### ISSUE TITLE
Negative Werte... Neue Spur ⁉️

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#1670]
Neue Spur beim Thema negative Werte....
Leider hat es auf mein letztes Ticket zum Thema wenig Bewegung seitens der Analyse gegeben.
Daher neuer Versuch mit neuer Erkenntnis.

Gestern habe ich ~21kwh in meinen ioniq geladen. Heute schaue ich gerade rein nachdem ich ne push Benachrichtigung bekommen dass gerade mit dem Laden begonnen wurde.

Was sehen meine müden Augen da. - 21kwh in der status Übersicht.

Kann der Wert beim Tageswechsel negativ übernommen worden sein? 
![Screenshot_20211030-105600_Firefox](https://user-images.githubusercontent.com/53753460/139526867-658e0861-0ec2-4aa2-b4f5-d8a58b6fd28b.jpg)
![Screenshot_20211030-105617_Firefox](https://user-images.githubusercontent.com/53753460/139526871-7360df12-77cb-43b4-a6db-39b1671f1666.jpg)

**Comment by Beme99** [comment]
Hallo Jan, ich habe das gleiche Problem, ebenfalls mit dem Modul SimpleEVSEWifi. Ich nutze einen S0 Zähler in der Wallbox und überlege ob es daran liegen könnte. Was hast Du für einen Zähler? Auch S0 oder Modbus?
Viele Grüße, Benjamin

**Comment by Beme99** [comment]
Vergesst meinen vorherigen Eintrag, bei mir ist openWB nicht die Ursache.
Ich nutze einen S0-Zähler, und EVSE-Wifi liefert für den Zählerstand (meterReading in getParameters) rückläufige Werte, d.h. der Zählerstand steigt nicht, sondern fällt beim neu anstecken. 
Habe das Problem bereits bei EVSE-Wifi gemeldet: https://board.evse-wifi.de/viewtopic.php?f=4&t=341&p=2383#p2383

**Comment by JanFellner** [comment]
Hi @Beme99,
haben die den Forumsbereich gelöscht? Ich kann da nix aufrufen obwohl ich dort nen Account habe...

https://board.evse-wifi.de/viewtopic.php?f=4&t=341&p=2383#p2383
-> nicht berechtigt

Oder hast du nen aktuellen Status?
Jan

**Comment by Beme99** [comment]
Hallo Jan, 
das ist ein Bereich mit speziellen Zugriffsberechtigungen (Beta-Tester).
Mathias, der Entwickler der EVSE-Wifi hat sich am 04.03. im Thread gemeldet:

> [](https://board.evse-wifi.de/viewtopic.php?f=4&t=341&p=2383#top)Danke fürs Melden, dieses Bugs. Da hab ich was im Kopf, dass wir dieses Problem eigentlich schon mal geslöst hatten. Aber ich werde mir das nochmal genauer ansehen, wie das zustande kommt. Ich denke, das werden wir lösen können.

Viele Grüße
Benjamin

**Comment by benderl** [comment]
Da dies anscheinend kein Fehler bei openWB ist, schließe ich hier mal ab.
