### ISSUE TITLE
 openWB/system/Timestamp im Nur Ladepunkt Modus nicht aktualisiert

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#1674]
Siehe https://github.com/evcc-io/evcc/discussions/1681#discussioncomment-1578584. Es scheint, also würde `openWB/system/Timestamp` im Nur Ladepunkt Modus nicht aktualisiert. Der Timestamp sollte aktualisiert werden damit evcc feststellen kann, dass die OpenWB auf Befehle reagiert, also "online" ist.

/cc @snaptec

**Comment by snaptec** [comment]
https://github.com/snaptec/openWB/commit/3dc29396eb3609544bf7f5a2e513d2d2f589d7e1
Fixed

**Comment by Pjg-Git** [comment]
> [3dc2939](https://github.com/snaptec/openWB/commit/3dc29396eb3609544bf7f5a2e513d2d2f589d7e1)
> Fixed

Date und Timestamp verwechselt im Nur Lademodus. Siehe evcc Link.
