### ISSUE TITLE
Mindest-SOC Einstellung verschwindet nach Aktivieren von mehr als einem Ladepunkt

### ISSUE THREAD

**Issue by Brovning** [snaptec/openWB#1704]
Hallo,

wenn ich nur 1 Ladepunkt konfiguriere, kann ich den Maximal-Soc und den Mindest-Soc unter "Ladeeinstellungen" --> "PV- und Min-PV" konfigurieren:

![openWB - EV-SoC-Ladung Mindest-SOC (1 Ladepunkt)](https://user-images.githubusercontent.com/39644775/141676716-c1432ebe-faa0-42b2-80fb-8ae3e567c940.jpg)

Sobald ich 2 Ladepunkte konfiguriere verschwindet die Möglichkeit einen Mindest-Soc zu konfigurieren und man kann nur noch einen Maximal-Soc konfigurieren:

![openWB - EV-SoC-Ladung kein Mindest-SOC (2 Ladepunkte)](https://user-images.githubusercontent.com/39644775/141676735-3d66f5d1-41c8-4372-847d-4ea9e3f0b2f4.jpg)

Ich gehe davon aus, dass es sich hierbei um einen Bug handelt.

installierte Version: 1.9.244

**Comment by benderl** [comment]
Das ist kein Bug, sondern "works as designed". Eine Implementierung würde einen größeren Umbau der Regelung nach sich ziehen.

**Comment by Brovning** [comment]
Oh, das ist aber ungünstig.
Wie kann ich eine Mindestladung mit 2 Wallboxen realisieren?

**Comment by benderl** [comment]
Derzeit ist es nicht automatisiert möglich. Mit der Version 2.0 (derzeit in Entwicklung) ist das auch mit mehreren Ladepunkten machbar.

**Comment by Brovning** [comment]
Was ist der geplante Veröffentlichungszeitpunkt der v2.0?

**Comment by benderl** [comment]
Wenn es keine größeren Probleme mehr gibt, wird noch dieses Jahr eine erste Testversion veröffentlicht. Die ist dann jedoch mit Vorsicht zu genießen und eher für freiwillige Tester und Entwickler gedacht.
