### ISSUE TITLE
Kein soc in Modbusdaten 

### ISSUE THREAD

**Issue by Whitytom** [snaptec/openWB#1713]
Von einem zweiten raspi frage ich die Openwb über Modbus ab. Dabei fehlt mir bei den Ladepunktdaten der soc, den die Openwb nach anfänglichen Schwierigkeiten von Corsa-e ermittelt. Kann der zusätzlich bereitgestellt werden?

**Comment by benderl** [comment]
Der Modbus Server wurde implementiert, um den Anforderungen an die KfW Förderung gerecht zu werden. Dort wird Modbus als Schnittstelle für den Netzbetreiber gefordert. Folglich sind dort auch nur potentiell für den Netzbetreiber relevante Infos vorhanden.
Für die eigene Nutzung bietet openWB MQTT oder eine Http API an. Dort sind die SoC Werte bereits abrufbar. Es sollte nach Möglichkeit auf MQTT gesetzt werden, da es am wenigsten Last erzeugt und openWB nicht regelmäßig gepollt werden muss.
