### ISSUE TITLE
Colors Theme - gewählter Preisbereich wird nicht markiert

### ISSUE THREAD

**Issue by riesi77** [snaptec/openWB#1750]
Wird im Colors Theme (Web) preisbasiertes Laden aktiviert und ein Wert gewählt, der innerhalb des Preisbereichs fällt, wird dieser in anderen Themes markiert, sodass man weiß, es wird für x Stunden geladen werden.
Im Colors Theme ist das leider nicht der Fall. Keine Markierung. Damit weiß man leider auch nicht genau, wie lange geladen werden würde.

**Comment by riesi77** [comment]
@benderl : Sollte das in der aktuellen Nightly schon funktionieren? Ich sehe leider noch keine Markierung:
![image](https://user-images.githubusercontent.com/67387975/144219848-51eb2e2b-e46e-4843-af98-8bcb30078f93.png)

**Comment by benderl** [comment]
@cshagen kannst Du das bitte prüfen?

**Comment by cshagen** [comment]
Ist ein Bug. Muss ich fixen.

**Comment by cshagen** [comment]
Gefixt im PR  #1762

**Comment by riesi77** [comment]
@cshagen , @benderl : Gerade in der nightly überprüft: Funktioniert perfekt. Herzlichen Dank!
