### ISSUE TITLE
Mqtt Topics für Nur Ladepunkt Modus inkonsistent

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#1757]
Aus dem Code:

```
openWB/set/isss/ClearRfid
openWB/set/isss/Cpulp1
openWB/set/isss/Current
openWB/set/isss/heartbeat
openWB/set/isss/Lp2Current
openWB/set/isss/parentCPlp1
openWB/set/isss/parentCPlp2
openWB/set/isss/parentWB
openWB/set/isss/U1p3p
openWB/set/isss/U1p3pLp2
```

Inkonsistenzen: 
- lp vorne vs hinten 
- lp groß vs klein
- lp2 angehängt, lp1 nicht
- Groß vs. Kleinschreibung des Topics

Wäre super, dass in v2 aufzuräumen

/cc @snaptec

**Comment by andig** [comment]
Mir fehlt auch das Topic um dem Ladepunkt eine RFID mitzugeben?

**Comment by andig** [comment]
Um den Ladepunkt programmatisch freischalten zu können, z.B. wenn ein bestimmtes Fahrzeug verbunden ist. Automatische Fahrzeugerkennung gibts bei evcc.

**Comment by benderl** [comment]
Evcc sendet also einen Tag an den Ladepunkt, damit der diesen Tag an Evcc zur Freischaltung sendet? Interessanter Ansatz, aber irgendwie seltsam.

**Comment by hhoefling** [comment]
git's irgendwo eweitere Infos...
Außer GPS fällt mir da nix ein.
Und wie gesagt ob auch der Stecker drin steckt weiss du ja erst wenn Strom beim Auto ankommt. (messbar)
Wenn ja dann war es wohl das richtige Auto
Aber zur Freigabe taugt das nicht..

**Comment by benderl** [comment]
> Was ist daran seltsam? Wenn meine Wallbox öffentlich erreichbar ist möchte ich, dass mein Fahrzeug mit PV lädt, aber nicht beliebige Fahrzeuge der Nachbarn. Natürlich kann ich mein RFID Tag auch dran halten, aber das geht auch automatisch. Oder ginge falls OpenWB die tag injection ermöglichen würde wie das z.B. bei der Warp der Fall ist.

Seltsam finde ich den Umweg über den Ladepunkt. Eine openWB als externer Ladepunkt hat keine eigene Sperre, sondern wird komplett über den Master gesteuert.

**Comment by hhoefling** [comment]
Oh, ich denke EVCC will in diesem Fall den Master spielen.

**Comment by benderl** [comment]
@andig  Sind die Tests abgeschlossen?

**Comment by andig** [comment]
Jetzt hast Du mich auf dem falschen Fuß erwischt- welche Tests? Das Thema hier war ja konsistentes Naming und dazu gabs bisher kein Update?

**Comment by benderl** [comment]
War auf #2294 bezogen. In 1.9 werden die Namen nicht mehr angepasst.

**Comment by andig** [comment]
Hab leider kein Feedback erhalten. Die Testerin war nach den end- und sinnlosen Runden über den Support wohl erschöpft. Machen wir hier zu als wontfix bis 2.0?

**Comment by benderl** [comment]
???

**Comment by andig** [comment]
> ???

Es gab x roundtrips mit dem Support zur CP Unterbrechung bei Nur Ladepunkt. Am Ende war die Erkenntnis aus #2294, dass das heute einfach nicht umgesetzt ist/funktioniert. Wenn Du da mehr Details willst lass uns gerne per Slack reden.

**Comment by benderl** [comment]
Ich bin da nicht der richtige Ansprechpartner.

**Comment by andig** [comment]
@benderl gibts denn für 2.0 eine neue Mqtt Struktur? Welche?

**Comment by benderl** [comment]
In 2.x ist vorgesehen, dass die Anbindung von Drittanbieter-Software über Modbus/TCP erfolgt.
