### ISSUE TITLE
EVCC Zugriffe

### ISSUE THREAD

**Issue by hhoefling** [snaptec/openWB#1792]
Beim Laden von modulconfiglp.php werden diese Zeilen ausgeführt.

Zeile 48:
			// read available vehicles for EVCC SoC module from web API
			$soc_evcc_vehicles = json_decode(file_get_contents('https://cloud.evcc.io/api/vehicles'), true);
			$firstentry=array("id" => "none", "name" => "Bitte auswählen");
			array_unshift($soc_evcc_vehicles , $firstentry);

Es werden die dort verfügbaren PKW eingelesen um für den Fall das der User das EVCC Module auswählen würde
eine PKW Liste anzeigen zu können.
Da ich kein EVCC Module verwend denke ich das es schöner wäre wenn das Zugriff auf EVCC erst erfolgen würde wenn das EVCC Module auch wirklich verwendet wird. 

Falls der dortige Server rumzickt, dann ziggt openWB auch und läuft beim Seitenaufbau auf einen Timeout.
Sehr unschön wenn mann EVCC gar nicht auf dem Schirm hat.

**Comment by benderl** [comment]
@andig Kannst Du da bitte mal nachsehen? Wäre sicher gut, wenn die Liste erst geladen wird, wenn sie auch benötigt wird, heißt im Browser mit JS. Als Beispiel kann das Tronity Modul genutzt werden.

**Comment by andig** [comment]
Da kann uns nur @Bucky2k helfen- ich habe keine OpenWB in der ich implementieren kann...

**Comment by Bucky2k** [comment]
@benderl Hi, die API abfrage hattest Du doch glaube ich selbst eingebaut oder wer war das? Derzeit wird der Abruf in Zeile 48 in der Tat für alle openWB Nutzer ausgeführt - das ist ja auch für EVCC und deren Server unnötige Last. Ich bin mir aber nicht sicher, wie dieser Request für die Listen-API direkt in das EVCC Modul verschoben werden kann/muss, damit es funktioniert.

Gruß

Bucky

**Comment by benderl** [comment]
Nein, das habe ich nicht "verbrochen". ;-)
https://github.com/benderl/openWB/commit/4e524ceb34b14316e2d10ca3d09d4ad338db801d

Ich hatte eben einen kurzen Test analog zu Tronity gemacht. Leider wurde das Abrufen der Liste wegen aktiviertem CORS auf dem EVCC Server vom Browser abgebrochen. Die unterstützten Fahrzeugtypen müssten dann von einem PHP-Skript auf der openWB abgerufen werden, welches wiederum in der modulconfiglp.php per Ajax abgerufen wird.

Freiwillige vor.

**Comment by andig** [comment]
> Leider wurde das Abrufen der Liste wegen aktiviertem CORS auf dem EVCC Server vom Browser abgebrochen. 

Das verstehe ich nicht. Abrufen der Liste geht doch bzw. ging bisher. In welchem Fall geht das jetzt hier nicht? Was sagt die Browserkonsole?

**Comment by andig** [comment]
@benderl CORS ergänzt:

```
< HTTP/2 200
< access-control-allow-headers: Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-origin: *
< content-type: application/json; charset=UTF-8
< content-length: 781
< date: Tue, 18 Jan 2022 15:36:25 GMT
```

**Comment by benderl** [comment]
Die Browser sind da restriktiver als PHP. Wird etwas von einer anderen Domain per JS geladen, dann wird geprüft, ob der Server dieser Domain das erlaubt. Dazu gibt es den CORS Header. Wenn es komplett im Browser laufen soll, müssten die Header angepasst werden.

Alternativ wird eine Anfrage an die openWB gestellt, welche dann in PHP von EVCC die Liste abruft und weitergibt.

**Comment by andig** [comment]
>  Wenn es komplett im Browser laufen soll, müssten die Header angepasst werden.

Done- haben wir uns überschnitten.

**Comment by benderl** [comment]
Bitte mal #1947 testen.
