### ISSUE TITLE
Feature: IEEE 1901 powerline for LAN communication

### ISSUE THREAD

**Issue by alagopus** [snaptec/openWB#19]
Using powerline for the LAN connections would eliminate the switch as a point of failure, and may greatly reduce cabling efforts. I have not enough electrical experience to evaluate the feasibility. Maybe https://roeebar.github.io/gr-plc/ would allow to implement it on the raspi side.

**Comment by snaptec** [comment]
If there is no Ethernet at the charging location it is recommended to use wifi instead.
Integrating powerline seems to be a massive amount of work where simpler solutions (wifi) just works.
