### ISSUE TITLE
Externe Steuerung im "Nur Ladepunkt" Modus funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#1956]
Wir wollen die owb im "Nur Ladepunkt" Modus steuern. Die verwendeten Topics entsprechen https://github.com/snaptec/openWB/blob/10bced471857f1c2af40e7b37dc8ba156d951746/runs/mqttsub.py#L1218.

Die Steuerung funktioniert prinzipiell, d.h. wir können feststellen dass das Auto verbunden ist/ lädt. Aber:

- [ ] der eingestellte Strom (`ADirectChargeAmps`) unter `openWB/lp1` oder `openWB/lp/1` wird nicht aktualisiert (das ist laut @snaptec erwartet)
- [ ] die Ströme `boolChargeStat` und `boolPlugStat` unter dem Ladepunkt werden nicht aktualisiert, bleiben auf `0` obwohl Fahrzeug verbunden
- [ ] die Ströme `APhase1...3` unter dem Ladepunkt werden nicht aktualisiert
- [ ] die Energie `kWhCounter` unter dem Ladepunkt wird nicht aktualisiert
- [ ] die OpenWB schickt teilweise keine oder nur verzögerte Updates über `openWB/system/Timestamp` obwohl `openWB/set/isss/heartbeat` laufend mit `1` beschrieben wird- Erwartung ist ein Update alle 10s:

      [openwb] TRACE 2022/01/22 12:14:42 recv openWB/system/Timestamp: '1642850072' <- letztes Update (müsste alle 10s kommen)
      [openwb] TRACE 2022/01/22 12:14:52 send openWB/set/isss/heartbeat: '1'        <- hb wird aktualisiert
      [openwb] ERROR 2022/01/22 12:14:54 heartbeat: timeout                         <- mehr als 10s vergangen, kein neuer Timestamp erhalten
      [openwb] TRACE 2022/01/22 12:15:02 send openWB/set/isss/heartbeat: '1'
      [openwb] ERROR 2022/01/22 12:15:04 heartbeat: timeout
      [openwb] TRACE 2022/01/22 12:15:12 send openWB/set/isss/heartbeat: '1'
      [openwb] ERROR 2022/01/22 12:15:14 heartbeat: timeout
      [openwb] TRACE 2022/01/22 12:15:22 send openWB/set/isss/heartbeat: '1'
      [openwb] TRACE 2022/01/22 12:15:24 recv openWB/system/Timestamp: '1642850092' <- plötzlich kommt ein Schwung verzögerter Updates
      [openwb] TRACE 2022/01/22 12:15:24 recv openWB/system/Timestamp: '1642850102'
      [openwb] TRACE 2022/01/22 12:15:24 recv openWB/system/Timestamp: '1642850112'
      [openwb] TRACE 2022/01/22 12:15:24 recv openWB/system/Timestamp: '1642850122'
      [openwb] TRACE 2022/01/22 12:15:32 recv openWB/system/Timestamp: '1642850132'

installierte Version: 1.9.250 (2022-01-06 13:12:43 +0100 [8bb88021] )

Refs https://github.com/snaptec/openWB/issues/1757
/cc @snaptec

**Comment by snaptec** [comment]
Was sagt unter Status das nur Ladepunkt log der openWB?

**Comment by snaptec** [comment]
Status url kopieren, Nur Ladepunktmodus aktivieren, einmal neustarten. 

Nun beobachten. 

Laut Log klappt hier eher die zählerauslesung generell nicht. 

On top dann bitte gleich einen Systembericht der openWB senden (Einstellungen, System, Support) und das Issue hier verlinken.

**Comment by andig** [comment]
Wir haben jetzt nochmal auf Nighly aktualisiert. Keine Fehler mehr im `isss.log` (Evtl. aufgrund https://github.com/snaptec/openWB/commit/64fbaa2b69b34c5c51113c13459e845f26758889?), aber dennoch keine Updates auf MQTT. Wir prüfen das jetzt nochmal durch, Systembericht folgt.

**Comment by andig** [comment]
> Status url kopieren, Nur Ladepunktmodus aktivieren, einmal neustarten.

Neustart nur über Shell möglich da Menüpunkt nicht mehr erreichbar.

Jetzt Auto (i3) verbunden. `openWB/lp/1/boolPlugStat` bleibt auf `0`. Ladekabel verriegelt nicht. Nur Ladepunkt Log ist leer: 

- ![WIAFH8OrDgGDpecj](https://user-images.githubusercontent.com/184815/150679226-dcbf5981-7b69-43ad-b84e-46191ee5c6ec.png)
- ![Ile6P1xAgHUKpobz](https://user-images.githubusercontent.com/184815/150679276-95211ec0-de9a-4d85-b52b-691d00bef525.png)

Meine These: OpenWB hängt irgendwo, zumindest "vergisst" es, auch MQTT zu aktualisieren. Kann es sein, dass die Updates nur auf eine Master OpenWB passieren anstatt auf den Ladepunkt? Das wäre natürlich sinnlos ;)

Systembericht senden aus Nur Ladepunkt Modus ist nicht möglich da Datenschutzbestimmung nicht akzeptiert werden kann und immer wieder Redirect auf die Nur Ladepunkt Oberfläche kommt (nerv...).

Nach rückstellen auf Normalbetriebsmodus wird plötzlich auch `openWB/lp/1/boolPlugStat` wieder aktualisiert.
Ticket ID: #67052275

**Comment by andig** [comment]
Auf MQTT ist folgendes los im Moment des "Ladestarts" (der nicht passiert):

    mosquitto_sub -t openWB/set/# -v -h <ip>
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/Current 16
    openWB/set/isss/Current 16
    openWB/set/isss/Current (null)
    openWB/set/isss/Current (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1
    openWB/set/isss/heartbeat (null)
    openWB/set/isss/heartbeat 1

Lp1 stellt sich vollkommen tot:

    mosquitto_sub -t openWB/lp/1/# -v -h <ip>

**Comment by andig** [comment]
Ich hab eine Ahnung. Kann es sein, dass die OpenWB die Nachrichten nur sieht, wenn sie als `retained` geschickt werden? Das würde es erklären...

Wie funktioniert der Empfangsprozess? Lauscht da etwas ständig oder nur alle 10s?

**Comment by snaptec** [comment]
geklärt per Slack.

**Comment by andig** [comment]
Lösung: MQTT messages *müssen* `retained` sein.
