### ISSUE TITLE
Ladelog leer

### ISSUE THREAD

**Issue by tobintax** [snaptec/openWB#196]
V 1.4 Stable. Frische Installation auf Ubuntu. 
Das Ladelog ist immer leer. Das heruntergeladene csv enthält lediglich "Start". 

Ich schließe nicht aus dass es ein Bediener Fehler ist, konnte bisher das Problem aber noch nicht lösen.

**Comment by snaptec** [comment]
Nach frischer Installation ist allerdings auch keine Ladung vorhanden !?

**Comment by tobintax** [comment]
Habe mich falsch ausgedrückt. Wollte damit sagen, dass es eine neue und m.E. saubere Installation ist. 
Inzwischen wurden 5-6 Ladungen über "Min+PV" durchgeführt.

**Comment by snaptec** [comment]
was gibt ein
`ls -lah /var/www/html/openWB/web/ladelog`
aus?

**Comment by tobintax** [comment]
Es funktioniert jetzt. Es war ein Berechtigungsproblem. Danke!
