### ISSUE TITLE
MQTT EVU: Hausverbrauch nur als Ganzzahl

### ISSUE THREAD

**Issue by Alligator09** [snaptec/openWB#1968]
openWB Version 1.9.244 

Beim Setzen des MQTT Topics "openWB/set/evu/W" ist mir aufgefallen, dass openWB bei Werten mit Nachkommastelle nicht richtig rechnet und stattdessen eine 0 annimmt. Wenn das Smartmeter (hier SDM 630) mal zufällig eine ganzzahlige Leistung misst, verarbeitet openWB den Wert korrekt.

Als Workaround formatiere ich die Leistung in openHAB so, dass sie keine Nachkommastellen hat, dann werden sie von openWB zuverlässig verarbeitet. (s. Diagramm unten: zunächst nur Spitzen, wenn zufällig eine Ganzzahl, am Ende, nach Abschneiden der Nachkommastellen, eine durchgängige Linie.)

Ist es gewünscht, dass openWB auf dem Topic keine Nachkommastellen verarbeitet, oder ist es ein Bug?

![grafik](https://user-images.githubusercontent.com/98495237/151257815-f9f164c2-e6f9-4501-8961-61f9991ad4d5.png)

**Comment by benderl** [comment]
Das ist absichtlich so und auch in der Modulkonfiguration so beschrieben.

**Comment by Alligator09** [comment]
Danke für die schnelle Antwort. Den Datentyp habe ich offensichtlich überlesen.
