### ISSUE TITLE
Auswahl Ladestromstärke bei "Sofort Laden"

### ISSUE THREAD

**Issue by iot4all** [snaptec/openWB#2]
Zur manuellen Steuerung der Ladestromstärke im Modus "Sofort Laden" wird ein Auswahlmenü benötigt. Hiermit soll die Ladegeschwindigkeit einstellbar gemacht werden.
Eine "Merkfunktion" für den zuletzt eingestellten Wert erspart wiederholtes Einstellen in diesem Modus.

**Comment by snaptec** [comment]
auf der index.php hinzugefügt
