### ISSUE TITLE
Release GUI Changes

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#2052]
PR https://github.com/snaptec/openWB/pull/1499 ist vor 8 Monaten gemerged worden. Bis heute ist die Funktion nur im Nightly verfügbar. Dadurch entstehen immer wieder Supportanfrage und Fehlkonfigurationen bei evcc da Leafs als Nissan konfiguriert werden.

Ich bitte um Prüfung, wie die Änderungen released werden können.

**Comment by benderl** [comment]
Es wird gerade eine neue Stable vorbereitet. Wie alle anderen Anpassungen kommt dann auch das aktuelle EVCC Modul mit rein.

**Comment by andig** [comment]
@benderl gibts einen Zeithorizont dazu? Nach so langer Zeit wäre es schön, die diesbezüglichen Supportanfragen auf evcc-Seite in den Griff zu kriegen.

**Comment by benderl** [comment]
Asap
