### ISSUE TITLE
Featurerequest: SmartHome Gerät erst nach bestimmter Tageszeit schalten

### ISSUE THREAD

**Issue by Schmattek** [snaptec/openWB#2081]
Mir würde folgende Funktion sehr helfen:

Ich möchte einen Shelly 1 bei PV-Überschuss erst nach einer bestimmten Uhrzeit schalten. Das Feature das ganze ab einer bestimmten Uhrzeit abzuschalten gibt es mit der Option "Spätestens fertig um: ... Uhr" ja schon. Eine Option "Frühestens einschalten um/nach: ... Uhr" wäre klasse.

Hintergrund ist, dass ich meine Wärmepumpe gerne gegen Nachmittag/Abend in den "Smart Grid" Modus bringen möchte und das Brauchwasser für den Abend mit PV-Strom heizen möchte, wenn davon noch genug da ist. Das ganze bringt mir allerdings morgens oder mittags nicht, da ich das Brauchwasser dort (noch) nicht benötige. Ich habe in den Einstellungen leider nichts gefunden, was ein Schalten des Shellys erst nach einer gewissen Uhrzeit erlaubt. Deswegen der Request.

**Comment by okaegi** [comment]
Diese Funktion ist bereits vorhanden. Schau mal in die neueste Nightly dort gibt es pro Smarthomedevice das folgende Attribute
Frühster Start um
Uhrzeit im 24 Stunden-Format, z.B. "14:45". Der Wert "00:00" schaltet die Funktion ab. Einschaltbedingungen gelten erst ab der definierten Uhrzeit. Ausschaltbedingungen gelten den ganzen Tag.
