### ISSUE TITLE
Pro fails to update

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#2103]
```
❯ curl -s -X POST —-data "update=1" http://192.168.0.107/connect.php
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>411 Length Required</title>
 </head>
 <body>
  <h1>411 Length Required</h1>
 </body>
</html>
```

Stack version is `0.9.14`

**Comment by snaptec** [comment]
Witzig, wenn ich deinen Befehl heruaskopiere und die IP anpasse erhalte ich den selben Fehler.
curl -s -X POST —-data "update=1" http://192.168.0.107/connect.php
(copy & Paste von dir)
wenn ich es selbst eingebe:
 curl -s -X POST --data "update=1" http://192.168.0.51/connect.php
geht es ohne Probleme.
Ich vermute deine Tastatur versucht intelligent zu sein und merged die -- vor data? Das würde dann auch die Fehlermeldung erklären. Alternativ mal nur "-d" nehmen

**Comment by andig** [comment]
Guter Tipp. Root cause ist hier: https://openwb.de/main/?page_id=771

Schau Dir mal die Anführungszeichen genau an ;). Dass die Quotes bei copy/paste falsch sind hab ich gesehen, dass das erste `-` auch falsch ist ist tricky...

**Comment by snaptec** [comment]
Fixed :)
