### ISSUE TITLE
 Ich möchte gerne mehr als drei go-e charger steuern-hat jemand eine idee

### ISSUE THREAD

**Issue by miwi-1209** [snaptec/openWB#2128]

**Comment by miwi-1209** [comment]
Ich möchte gerne mehr als drei go-e charger steuern-hat jemand eine idee

**Comment by benderl** [comment]
Das wird mit openWB nicht funktionieren. In der 2.0 kann man mehr konfigurieren, jedoch wird dann das Lastmanagement deaktiviert.

**Comment by miwi-1209** [comment]
wann kommt denn die 2.0

**Comment by benderl** [comment]
Eine Alpha Version, in der ausschließlich openWB Ladepunkte und SmartWB unterstützt werden ist bereits verfügbar. Ein fixes Release Datum gibt es bis jetzt nicht.

**Comment by miwi-1209** [comment]
Vielen Dank für die Info
