### ISSUE TITLE
NaN im Theme colors 

### ISSUE THREAD

**Issue by edeckert** [snaptec/openWB#2139]
Version: 1.9.262 (Stable)
Theme: colors

meine Konfiguration:
SMA Home Manager 2.0
Varta Pulse Neo 6,5
CUPRA Leon (über EVCC)

der Aktuelle Gesamtverbrauch wird häufig nur als NaN angegeben:
![B34E2215-DAB9-4A6B-BD87-527A4C9C73F3](https://user-images.githubusercontent.com/91415525/162564350-e9b9ef67-007d-428b-8dc9-05f3afaf305a.png)

**Comment by benderl** [comment]
Wird der Hausverbrauch auch im Standard Theme so angezeigt? Wenn das nur im Colors Theme so ist, bitte im Forum melden.

**Comment by benderl** [comment]
Da keine weitere Rückmeldung kommt, schließe ich hier ab.
