### ISSUE TITLE
SOC-Module myopel und mypeugeot entfernen

### ISSUE THREAD

**Issue by miradarya** [snaptec/openWB#2220]
Es kommt seit einiger Zeit regelmäßig vor, dass neue Nutzer die veralteten Module soc_myopel oder soc_mypeugeot einrichten, die jedoch mittlerweile veraltet sind und nicht mehr funktionieren. Aus meiner Sicht sollten die Module entfernt werden oder zumindest prominent als veraltet gekennzeichnet werden mit Verweis auf das PSA-Modul.

**Comment by benderl** [comment]
Wenn die beiden Module eh nicht mehr funktionieren, können sie wirklich einfach entfernt werden. Generell wäre eine Migration zum PSA Modul natürlich besser. Das könnte in der `runs/updateConfig.sh` gemacht werden.
