### ISSUE TITLE
Featurewunsch: Bestimmten SoC bis zu vorgegebenem Zeitpunkt laden

### ISSUE THREAD

**Issue by DoctorMorris** [snaptec/openWB#2261]
Ich weiß nicht, ob es der richtige Weg ist, aber ich äußere hierüber auch mal einen Vorschlag. Es wäre hilfreich, wenn man beim Einstecken standardmäßig gefragt würde, wann man das Auto wieder benötigt (Datum und Uhrzeit) und mit welchem Mindest-SoC. Diese Information könnte man nutzen, um die Ladung bis zu einem bestimmten Zeitpunkt als PV oder Min+PV Ladung laufen zu lassen, um sie dann aber automatisch falls nötig rechtzeitig automatisch auf Sofortladen zu wechseln. Falls dies aus welchen Gründen auch immer nicht möglich ist, sollte eine Warnung per E-Mail erfolgen, damit man rechtzeitig manuell eingreifen kann, z.B. bei Ladeproblemen am Fahrzeug. Das kann man bestimmt extern über ioBroker mit MQTT o.ä. realisieren, aber eigentlich wäre es super, wenn die Box das selbst könnte. Die Ladecharakteristik müsste dann die OpenWB natürlich grob kennen, ggf. müsste man die Kapazität der Fahrzeugbatterie dann auch irgendwie einstellen können. Die Automatik wäre wie beschrieben dann relativ dumm, aber eigentlich schon sehr hilfreich. Mit Kenntnis der Wettervorhersage und des zu erwartenden Hausverbrauchs könnte man natürlich auch noch eine viel intelligentere Steuerung realisieren, müsste aber auch mehr Daten programmieren und das würde man dann vermutlich besser im ioBroker o.ä. programmieren.

**Comment by LKuemmel** [comment]
In openWB 2.0 kann für jedes Fahrzeug ein Ladeprofil erstellt werden. Dort kann im Lademodus Zielladen ein Soc oder Enregiemenge angegeben werden, die zu einer bestimmten Uhrzeit erreicht werden soll. Es kann ein Datum eingegeben werden oder einzelne Wochentage. Dann wird zunächst mit PV-Strom geladen und wenn damit das Ziel nicht erreicht wird, wird mit Netzbezug geladen.
