### ISSUE TITLE
Update-Problem Master/Client

### ISSUE THREAD

**Issue by hhoefling** [snaptec/openWB#2318]
Im Forum ist schon öfters von Problemen mit dem gleichzeitigen Update von Master/Client berichtet worden.
Der Grund könnte darin liegen das das Scipt update.sh und in der folge dann auch atreboot.sh
auf beiden System verschieden aufgerufen wird.

1)  von mqttsub.py mit Home: /home/pi und User pi  für das Update des Clienten.

2)  von updatePerformNow.php mit Home /var/www/html/openWB/web/settings  und User www-data  für das Update der Master.

updatePerformNow sollte "sudo -u pi"  verwenden und das Update Script sollte geprüft werden ob pi für alle Aufgaben korrekt ist.

**Comment by benderl** [comment]
Ich tippe eher auf nicht identische Topics. Siehe auch https://github.com/snaptec/openWB/commit/bd73d07a908cd39924dcb6806984e6a2f8abccda
