### ISSUE TITLE
Mqtt: verbaute 1p3p Umschaltung ausweisen

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#2325]
Für Nutzung mit externem HEMS wäre es schön, wenn wir erkennen könnten ob die Phasenumschaltung verbaut ist. Aktuell muss ein Anwender dies separat konfigurieren um Phasenumschaltung z.B. mit evcc nutzen zu können.

**Comment by benderl** [comment]
Ist leider so, dass die Hardware das nicht hergibt.

**Comment by andig** [comment]
Wir löst openWB das dann- Anwendereinstellung? Falls ja: lässt sich die Einstellung über mqtt publizieren?

**Comment by benderl** [comment]
Es gibt in 1.9 keine saubere Lösung dafür. In 2.0 ist es besser umgesetzt.

**Comment by andig** [comment]
@benderl gibts schon eine Doku, wie das in 2.0 gelöst wird die ich verwenden könnte?

**Comment by benderl** [comment]
Nein, da in der 2.0 noch gar keine lokalen Ladepunkte unterstützt werden.
