### ISSUE TITLE
Horizontal swipe gestures undermine kiosk mode (history)

### ISSUE THREAD

**Issue by webermax** [snaptec/openWB#2362]
...additional CLI flags might help, e.g. (Chromium):

```
# home/pi/.config/lxsession/LXDE-pi/autostart

@chromium-browser --incognito --disable-pinch --overscroll-history-navigation=0 --kiosk <URL...>
```

**Comment by benderl** [comment]
Can you please create a pull request?

**Comment by webermax** [comment]
Love to, but so far I couldn't figure out how to address the internal display (unsuccessful keywords: "Kiosk, Chrome/Chromium, Firefox, Display...").

Is it a specific "module", are config files written directly?

**Comment by webermax** [comment]
...this could be the correct location to fix it permanently(?)

https://github.com/snaptec/openWB/blob/master/web/tools/lxdeautostart

**Comment by benderl** [comment]
Seems like there are two places to fix. The one you already found and another in `runs/atreboot.sh`. https://github.com/snaptec/openWB/blob/130dca32cfb5524e1fa816f2ff5eb9b4acab6e81/runs/atreboot.sh#L99
I would suggest that `atreboot.sh` also just copies the file you found.

Seems also a bit weired, as there is an update procedure to disable swige gestures: https://github.com/snaptec/openWB/blob/130dca32cfb5524e1fa816f2ff5eb9b4acab6e81/runs/atreboot.sh#L370

I will have a look at this and implement a file version check similar to the one used in 2.0. https://github.com/openWB/core/blob/dbb259a5dd048f22d0c106880eb7bf3956d90e75/runs/atreboot.sh#L80

**Comment by webermax** [comment]
Hm, found it, too (commented in pull request).

So [atreboot.sh](https://github.com/snaptec/openWB/blob/130dca32cfb5524e1fa816f2ff5eb9b4acab6e81/runs/atreboot.sh#L370) searches for `@chromium-browser --incognito --disable-pinch --kiosk http://localhost/openWB/web/display.php` in [lxdeautostart](https://github.com/snaptec/openWB/blob/master/web/tools/lxdeautostart).

Then the script would replace it with the correct flag(!).

**Comment by benderl** [comment]
Please check current master with #2364
