### ISSUE TITLE
soc_evcc, rate limiting

### ISSUE THREAD

**Issue by nufer** [snaptec/openWB#2399]
Ich erhalte vom soc_evcc immer wieder die folgenden Einträge im Log:

 Error from EVCC: 2022/09/08 11:17:49 rpc error: code = Unknown desc = rate limit exceeded (max 1 req/min), slow down or contact info@evcc.io if you need support (LV0) at 84 getAndWriteSoc modules/soc_evcc/main.sh
2022-09-08 11:17:44: PID: 5211: Lp1: Requesting SoC (LV0) at 73 getAndWriteSoc modules/soc_evcc/main.sh
2022-09-08 11:17:44: PID: 5211: Lp1: timer = 20005 intervall: 4320 intervallladen: 720 (LV1) at 100 main modules/soc_evcc/main.sh

Den letzten Eintrag habe ich um die Werte intervall und intervall laden ergänzt um den Fehler besser eingrenzen zu können.

Den Wert timer kann ich auf dem Filesystem auf 0 setzen, die 20005 werden aber immer wieder geschrieben, woher weiss ich nicht.

Version: aktuelles Stable 1.9.275

**Comment by benderl** [comment]
Wegen Inaktivität geschlossen.
