### ISSUE TITLE
idee: unterstützung bluetooth beacon

### ISSUE THREAD

**Issue by ka7** [snaptec/openWB#24]
Idee:
im Auto ist ein Bluetooth beacon installiert ( dass alle X sekunden ein "ping" aussendet )
Raspi ( der 3er hat BT ) erkennt das, und schaltet das ganze damit frei.
-> Einfacher als ein Schlüssel-schalter, RFID, ...

**Comment by snaptec** [comment]
Gute Idee, aber:
der Raspberry ist aber nicht zwangsweise in der Wallbox.
Dieser kann auch im Verteiler bzw irgendwo im Lan sitzen.
Zudem kann man ja bis zu 3 Ladepunkte realisieren, natürlich mit nur einem Raspberry.

Wenn der Ladepunkt so zugänglich ist ist die Frage ob man "im freien" einen Raspberry haben möchte?

Wäre es da nicht eher sinnvoll im Lan zu schauen ob z.B. das Smartphone "Zuhause" ist und anhand dessen den Lademodus einstellen (web trigger)?
