### ISSUE TITLE
CP Unterbrechung funktioniert nicht im "Nur Ladepunkt" Modus

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#2400]
Siehe https://openwb.de/forum/viewtopic.php?f=4&t=5646 und https://github.com/evcc-io/evcc/discussions/4010#discussioncomment-3596163

**Comment by LKuemmel** [comment]
Die CP-Unterbrechung ist in #2294  enthalten.

**Comment by andig** [comment]
@LKuemmel da steht:

> Phasenumschaltung und CP-Unterbrechung erfolgt in Threads und blockieren nicht mehr den Daemon.

bedeutet Deine Antwort zusätzlich, dass sie aktuell einfach gar nicht implementiert ist oder fehlt?

Kommt #2294 vor 2.0 oder müssen wir darauf warten? Wäre es- da der PR ja schon länger auf ist- möglich CP vorher nachzurüsten?

**Comment by benderl** [comment]
Der PR und damit auch CP-U kommt rein, wenn die letzten bekannten Probleme mit den aktuellen Modulen behoben sind, da es doch eine größere Anpassung mit entsprechendem Fehlerpotential ist.

**Comment by LKuemmel** [comment]
Die CP-Unterbrechung funktioniert mit der aktuellen Stable auch im NurLadepunkt-Modus.
