### ISSUE TITLE
Ladeleistung falsch wiedergegeben

### ISSUE THREAD

**Issue by martingruening** [snaptec/openWB#2410]
Setup: Zwei OpenWB series2 standard+, beide auf 1.9.277,
LP1 ("Carport") ist Master, LP2 ("Einfahrt") ist als "nur Ladepunkt" konfiguriert

Folgender Zustand ergibt sich (kein Fahrzeug zum Laden angeschlossen)

![Screenshot 2022-09-19 095031](https://user-images.githubusercontent.com/36659742/190972912-83280f99-21d9-4702-901b-3b0b8130fc80.png)

Problem: Es wird eine Ladeleistung angezeigt, die real gar nicht da ist (beide Ladepunkte nicht in Nutzung)

Nebenbei ist der Hausverbrauch auch noch falsch wiedergegeben mit 0 Watt (das ist aber nicht Gegenstand dieses Issues, nur eine Nebenbeobachtung). Alle Werte für EVU und PV kommen aus dem lokalen OpenEMS System.

Es zeigt sich das gleiche Bild auch in den MQTT-Kanälen:
openWB/global/WAllChargePoints = 1377
openWB/lp/1/W = 0
openWB/lp/2/W = 0

**Comment by martingruening** [comment]
Nachtrag: im Debug Log finde ich häufig
`/var/www/html/openWB/modules/extopenwb/main.sh: Zeile 78: [: None: Ganzzahliger Ausdruck erwartet.`

Ich vermute einen Parsing Fehler. OpenEMS Version ist 22.4.

**Comment by LKuemmel** [comment]
Der Fehler "Ganzzahliger Ausdruck erwartet" wurde in der Nightly beseitigt. Vor dem Update bitte ein Backup erstellen.

**Comment by benderl** [comment]
Die aktuelle Stable enthält ebenfalls den Fix.
