### ISSUE TITLE
Ungenutzter Code in regel.sh?

### ISSUE THREAD

**Issue by MiOrt** [snaptec/openWB#2489]
Kann es sein, dass in der regel.sh ein ungenutzter Codeblock mitgeschleift wird? Gem. den Einstellungen der Regelgeschwindigkeit (misc.php) kann die entsprechende Variable die Werte 0, 2 oder 3 annehmen. Warum hier der Wert 1 ausgespart wird, ist nicht dokumentiert. Gleichzeitig wird in der regel.sh jedoch auf den Wert 1 geprüft. Zudem sollte der weiter unten stehende Block mit der Prüfung auf dspeed == 3 hochgezogen werden, so dass alle die Regelgeschwindigkeit betreffenden Programmteile zusammen stehen.

> if [[ $dspeed == "1" ]]; then
	if [ -e ramdisk/5sec ]; then
		sleep 5 && ./regel.sh >> /var/log/openWB.log 2>&1 &
		rm ramdisk/5sec
	else
		echo 0 > ramdisk/5sec
	fi
fi

**Comment by benderl** [comment]
Mag sein. Es gab mal eine schnellere Ausführung alle 5 Sekunden. Das war dann die fehlende 1.
Da es nicht stört, investieren wir unsere Arbeitszeit lieber in 2.0.
