### ISSUE TITLE
tip: code check tools (shellcheck, pylint)

### ISSUE THREAD

**Issue by ka7** [snaptec/openWB#25]
ich hab mal zum spass tools wie "pylint" (checkt python code gegen den pip-8 coding-style) oder "shellcheck" (checkt shell-scripte auf verbesserungs-potential) gegen den source-code laufen lassen.
Findet einiges... muss aber nichts heissen
generell hilft aber "sauberer code" beim zusammenarbeiten und fehler vermeiden.

**Comment by snaptec** [comment]
Optimierungspotential ist natürlich immer da. Pull Requests willkommen :)

**Comment by snaptec** [comment]
Danke.
Hast du getestet ob die Änderungen problemlos funktionieren?
