### ISSUE TITLE
Support für SDM72 als Separate Leistungsmessung bei SmartHome 2.0

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#2541]
Der SDM120 ist der günstigste Modbus 1 Phasen Zähler.
Der günstigste SDM72 Modbus Drehstrom Zähler wird heute leider nicht unterstützt wäre aber für die Leistungsmessung interessant.
Dieses Ticket als aufhänger für einen PR, ich schaus mir jetzt mal an.

**Comment by DetMoerk** [comment]
Sdm72 V2 als Modbus wird ohne Probleme in Smarthome 2.0 unterstützt. Läuft an meiner WP als Leistungsmesser.

VG
Det

**Comment by JanFellner** [comment]
Hi Det,

hast du hierfür den SDM 630 konfiguriert?
![image](https://user-images.githubusercontent.com/53753460/205739679-892e8f94-a8ce-4191-ae61-33d6760fb5c8.png)

Ich sehe zwar die Leistung aber interessanterweise keine Energiemenge...
Bei den SDM120 sehe ich dies.

Das Mapping der Modbus Adressen / Register bezüglich Leistung und Energie ist zwischen SDM630 und SDM72 identisch...

**Comment by DetMoerk** [comment]
Ja, ist als SDM630 konfiguriert. Ist dein SDM72 ein V2? Ich hab den V2. Der wird wohl in der Zwischenzeit in den Kits bei openWB mitgeliefert, da SDM630 kompatibel. Evtl. gibt es einen Unterschied zwischen V2 und älteren Versionen.
Ich hab den SDM72 V2 auch auf meinem Testsystem mal als PV/EVU Kit konfiguriert, funktioniert auch problemlos. 

VG
Det

**Comment by JanFellner** [comment]
Neuer Tag. Werte sind da. ;]
![image](https://user-images.githubusercontent.com/53753460/205841687-96c1d12f-c6d3-4d4a-83c2-d3b7b284cc92.png)
