### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by ka7** [snaptec/openWB#26]
momentan scheint das Projekt nur deutsch zu unterstützen.

eventuell sowas ?
https://www.linuxjournal.com/content/internationalizing-those-bash-scripts
( verwenden von PO files in bash )

... same should be possible for Python, like
https://docs.python.org/3/library/gettext.html

**Comment by snaptec** [comment]
im moment gibt es da noch einiges anderes, daher stelle ich das mal hinten an.
