### ISSUE TITLE
Regelungsoffset für PV-Ladung

### ISSUE THREAD

**Issue by davipet1** [snaptec/openWB#2627]
Hallo,
gibt es einen Parameter um ein Regelungsoffset auf PV-Ladung zu setzen?
Für PV-Ladung mit EV Priorität gibt es einen Offset für den Speicher. Bei Speicher-Priorität wird offenbar auf 0 am EVU-Übergabepunkt geregelt.
Ich habe einen ELWA (Elektrisch Warm-Wasser), den ich auch auf PV regele. Meine PV-Anlage hat im Peak genug Leitung um sowohl den ELWA (mit 3kW) als auch das EV mit 11kW zu versorgen. Reicht die Leistung nicht, würde ich gerne den ELWA priorisieren. Da aber auf 0 geregelt wird, habe ich keinen Spielraum um den ELWA hoch zu regeln. Hier würde ich mir einen einstellbaren Offset wünschen. (Alle bei 100% Speicher - also mit Speicher-Prio)
Ich hoffe das Anliegen ist verständlich ausgedrückt.

Gruß

David

**Comment by benderl** [comment]
In den PV Einstellungen kann bereits ein manueller Regelpunkt definiert werden. Für das optimale Zusammenspiel zwischen openWB und Elwa sollte letzterer im SmartHome 2.0 der openWB eingebunden werden.
