### ISSUE TITLE
Smarthome nicht mehr umschaltbar 1.9.296

### ISSUE THREAD

**Issue by martin-zh** [snaptec/openWB#2650]
Seit der 1.9.296 kann man auf der Hauptseite den Modus der Smarthome Geräte nicht mehr umschalten, zb. auf manuell. Link scheint noch da zu sein, Gerät bleibt aber auf Automatik.

Siehe:
https://openwb.de/forum/viewtopic.php?p=82087#p82087
https://www.openwb.de/forum/viewtopic.php?p=81915#p81915

**Comment by benderl** [comment]
Sollte mit #2654 und #2655 behoben sein.
