### ISSUE TITLE
Darstellung Fehler Theme Colors

### ISSUE THREAD

**Issue by chfaurie** [snaptec/openWB#2651]
Die Schriftart im Theme Color ist leider falsch und Symbole werden. In diesem Fall beim iPhone 12 pro Safari Browser.
Im iPad desktop und auch im Responsive Mode (Safari) wird alles korrekt angezeigt.

![C92EB8F3-EE67-4EAC-B78B-9F4929DCCDBB](https://user-images.githubusercontent.com/94569403/224707364-253d6e77-6e18-498c-8310-17c952f5cd86.png)
 als Kasten angezeigt. ![image](https://user-images.githubusercontent.com/94569403/224709453-715011bb-e20d-4545-91be-87703abd9099.png)

Die Linie vom oberen Kasten wird auf dem iPhone auch nicht angezeigt.

**Comment by benderl** [comment]
Bitte den entsprechenden Supportbeitrag im Forum nutzen. Das Theme gehört nicht zum Standard und wird daher auch nicht offiziell supported.
