### ISSUE TITLE
Publish 2.0 api docs

### ISSUE THREAD

**Issue by andig** [snaptec/openWB#2786]
It would be nice if the 2.0 api could be documented. According to https://github.com/evcc-io/evcc/issues/9556 it seems there are breaking changes.

**Comment by TobiasHuber1980** [comment]
Ist zwar für die openWB Pro, aber immerhin ein bißchen Doku:
https://openwb.de/main/?page_id=771#schnittstelle

**Comment by andig** [comment]
Hat aber leider nichts mit der OpenWB zu tun :/

**Comment by TobiasHuber1980** [comment]
@andig Update:
https://openwb.de/forum/viewtopic.php?t=7662

**Comment by benderl** [comment]
Dann schließe ich hier mal ab. Der Link zur Modbus/TCP Dokumentation:
https://openwb.de/main/wp-content/uploads/2023/10/ModbusTCP-openWB-series2-Pro-1.pdf
