### ISSUE TITLE
Connection to Modbus TCP not working

### ISSUE THREAD

**Issue by atze09** [snaptec/openWB#2796]
Hallo zusammen,

Mit der neuen Software 2.0 (genauer gesagt 2023-09-27 10:18:20 +0200 [380ac109e])
Bekomme ich weder mit einem Programm auf dem Windows Rechner noch mit EVCC Zugriff auf ModbusTCP der openwb.
Openwb Series2 is auf Nur Ladepunkt (secondary) eingestellt, muss ich sonst noch irgendwelche Einstellungen für ModbusTCP machen?

Ich würde gerne probieren, dass EVCC die Ladesteuerung über die openwb übernimmt.
Vielen Dank schon einmal

**Comment by benderl** [comment]
Modbus wurde erst nach dem Release integriert. Du musst auf die aktuelle Master Version wechseln.

**Comment by atze09** [comment]
> Modbus wurde erst nach dem Release integriert. Du musst auf die aktuelle Master Version wechseln.

Das war die Ursache, danke. Connection funktioniert, nur aktuell mit timeouts aber das ist ein anderes Thema.
