### ISSUE TITLE
"Zurück"-Button auf der Statusseite

### ISSUE THREAD

**Issue by michaelstaemmler** [snaptec/openWB#293]
Auf allen Seiten gibt es **links oben** entweder
- einen Zurück-Button, oder aber
- einen Zurück-Tab

welcher zurück auf die Hauptseite führt.

So etwas fehlt noch auf der Statusseite (mir ist bewusst dass es einen Button oberhalb des GSI-Graphs gibt, dieser ist allerdings nicht so gut zu erreichen).

**Comment by MiOrt** [comment]
Statusseite wurde an neues Layout mit Navbar und Footer angepasst. Zurück nur noch über Navbar notwendig. Layout der Seiteninhalte ist aber noch nicht final, zwar schon teils responsive aber noch mit Luft nach oben :-)
