### ISSUE TITLE
URls nicht escaped

### ISSUE THREAD

**Issue by Roland-git** [snaptec/openWB#3]
Die URLs für EVU Zähler und SOC werden nicht gespeichert.
Wenn ich die URL hinterlege und dann speicher ist meine Eingabe wieder verschwunden.

**Comment by snaptec** [comment]
Kann ich nachstellen, Fehler gefunden.
fix im nächsten release!

**Comment by snaptec** [comment]
Sollte nun klappen, wird im backend escaped.
Falls nicht, bitte wieder öffnen
