### ISSUE TITLE
enhancement: input type="number"

### ISSUE THREAD

**Issue by tpd-opitz** [snaptec/openWB#301]
Die meisten Eingabefelder erwarten Zahlenwerte. Auf Smartphones wird die aphabetische Tastatur angeboten, wenn man in so ein Feld tippt, denn der Typ der Eingabefeler ist überall "text":

```
 	<b><label for="nachtsocs1">Nacht SOC Sonntag bis Donnerstag:</label></b>
	<input type="text" name="nachtsocs1" id="nachtsocs1" value="70"><br>
```

Der Typ sollte auf "number" geändert werden, um die Eingabe zu vereinfachen.

**Comment by MiOrt** [comment]
Das wird mit Anpassung auf Bootstrap 4 nach und nach geändert. Dauert aber noch etwas.

**Comment by benderl** [comment]
Inzwischen sollten alle Felder entsprechend überarbeitet sein.
