### ISSUE TITLE
feature request: Morgens Laden tageweise aktivierbar

### ISSUE THREAD

**Issue by tpd-opitz** [snaptec/openWB#302]
Ich nutze das Nacht-Laden mit SOC-Begrenzung, um meine ZOE nicht auf 100% zu laden.

Im Winter möchte ich aber vor dem Losfahren zusätzlichen Strom für das Vorheizen bereit stellen, unabhängig von SOC des Fahrzeugs. Allerdings benötige ich diese "Ladeleistung" nur Werktags.

Ich möchte also das Morgens Laden nur für einzelne Tage aktivieren, mindestens jedoch (wie Nacht-Laden) das Wochenende ausnehmen können. 

- Minimallösung: Checkbox "nur Werktags"
- Maximal-Lösung: Einstellung von Start- und Endzeit je Wochentag

**Comment by snaptec** [comment]
Das Morgens Laden ist in der Beta/Nightly je Tag mit unterschiedlicher Stromstärke & Uhrzeiten einstellbar.
