### ISSUE TITLE
Bezeichnung der einzelnen Ladepunkte vom Nutzer veränderbar

### ISSUE THREAD

**Issue by e-lmo** [snaptec/openWB#34]
Bei mehr als einem Ladepunkt erscheint es mir sinnvoll, dem Nutzer die Möglichkeit zu geben, für diese eigene Bezeichnungen festlegen zu können. Z.B. Carport links, Garage, etc.

Dafür könnte man in den einzelnen Modulen unter "Erster Ladepunkt", "Zweiter Ladepunkt" ein editierbares Textfeld einfügen, in dem die bisher auf der OpenWB-Hauptseite verwendeten Bezeichnungen "Ladepunkt1, "Ladepunkt2" als Vorgabe stehen.
Da z.B. im Ladelog lediglich die Ziffer des Ladepunkts auftaucht, ist ein langer Text möglicherweise nicht überall darstellbar. Deshalb sollte zumindest auf der Hauptseite die Bezeichnung einmal im Format "LP1: Carport links", "LP2: Garage" gemeinsam erscheinen.

**Comment by snaptec** [comment]
In beta 0.99.5 eingefügt.
Passt so?
Bitte um Bestätigung

**Comment by e-lmo** [comment]
Die Richtung stimmt schon einmal.

Allerdings sind zwei weitere Stellen auf der Hauptseite noch mit LP1/2 bzw Ladepunkt1/2  beschriftet.
Weitere Bezeichnungen in dem Format finden sich unter Einstellungen, Ladelog und Status.
Ich glaube nicht, dass eine komplette Umbenennung praktikabel ist. 

Trotzdem möchte ich dass auch weitere Nutzer außer mir die einzelnen Ladepunkte intuitiv zuordnen und bedienen können.
Deshalb sollten die individuellen Bezeichnungem zumindest auf der Hauptseite verwendet werden und zusätzlich einmal im Format "Ladepunkt1: {individueller Name1}", "Ladepunkt2: {individueller Name2}" gemeinsam erscheinen. Zum Beispiel unter "aktuelle/Letzte Ladung"

**Comment by snaptec** [comment]
v0.99.51

So in etwa?

**Comment by e-lmo** [comment]
Ja, das sieht gut aus!
