### ISSUE TITLE
Remove clientside authentication validation

### ISSUE THREAD

**Issue by Zilor** [snaptec/openWB#372]
openWB uses JavaScript to handle the entire login/authentication process for it's setting webpage.
This allows a person to simply bypass the login process by
- Turning off JavaScript
- Modifying the executed JavaScript with a debugger tool
- Reading the plain password by looking at the source code of the webpage
(The password is also exposed in plaintext at the web/misc.php site) 

I suggest to make the authentication server side, with a encrypted password, etc.
.htaccess can be used to secure the web interface, until a patch comes out

**Comment by benderl** [comment]
PR #423 addresses this issue.

**Comment by snaptec** [comment]
Thanks!
