### ISSUE TITLE
No Offset recognition during Min+PV, if Uberschuss == 0

### ISSUE THREAD

**Issue by Skibbie** [snaptec/openWB#397]
changing line 38 in minundpv.sh into following, seems to fix it.

llneu=$(( llalt + ( (uberschuss - schaltschwelle) / 230 / anzahlphasen)))

**Comment by snaptec** [comment]
fixt folgt

**Comment by Skibbie** [comment]
Sag Bescheid, wenn ich etwas testen soll. ;-)

Nur eine Idee: könnte man nicht für minundpv einfach das nurpv Skript etwas
abändern und über einen Parameter steuern, dass bei minundpv nur der
Mindestüberschuss und der Abschaltüberschuss nicht beachten werden? Dann
bräuchte man den Teil der Regelung etc. nur einmal coden.
Oder gibt's da noch mehr Unterschiede?


snaptec <notifications@github.com> schrieb am Mo., 9. März 2020, 07:56:

**Comment by snaptec** [comment]
Ein paar mehr sind es schon. Problem sollte derweil behoben sein.
