### ISSUE TITLE
Andere Rpi Usernamen unterstützen

### ISSUE THREAD

**Issue by Skibbie** [snaptec/openWB#400]
Ich habe meinen Standard User "pi" umbenannt.
Nun musste ich in mehreren Dateien diesen Namen ändern.

Kann man dort evtl. eine globale Variable einbauen? ($USER)
Gibt es sowas im Rpi?
Oder ist das gar nicht gewünscht?

**Comment by snaptec** [comment]
Derzeit keine Kapazitäten um das zu testen / implementieren
