### ISSUE TITLE
enhancement: consistent logging graphs

### ISSUE THREAD

**Issue by tpd-opitz** [snaptec/openWB#421]
betrifft: Ver 1.7.302Nightly 

Die Darstellung der Grafen ist bei "Tag" anders als bei "Langzeitansicht".
![logging-longterm](https://user-images.githubusercontent.com/14850347/77626913-556fb700-6f46-11ea-86f4-6d4fd67133ba.png)

![logging-day](https://user-images.githubusercontent.com/14850347/77626880-4983f500-6f46-11ea-9f5c-6bcd6e7afb93.png)

Der Graf der "Langzeitansicht" ist für mich viel verständlicher. Bitte den Graf der Tagesansicht anpassen, so dass für die einzelnen Kurven die selben Daten wie in der Ansicht "Tag" genutzt werden

**Comment by snaptec** [comment]
Das ist nicht so leicht möglich.
Die Langzeitansicht basiert auf Watt Werten.
Der Tagesgraph basiert auf Zählerständen.
Heißt bei Langzeit gibt es einen Wert Speicher, beim Tagesgraph hingegen gibt es Speicherimport & Speicherexport.

**Comment by tpd-opitz** [comment]
Den Einwand verstehe ich nicht.  
Aus meiner (naiven) Sicht muss es doch möglich sein, beide Reports über die selben Daten laufen zu lassen, nur dass der Endpunkt im Tages-Report nicht mer relativ zur aktuellen Urzeit, sondern fix ist.

**Comment by snaptec** [comment]
es werden aber unterschiedliche Daten zur Erzeugung herangezogen.

**Comment by tpd-opitz** [comment]
Das sagtest Du bereits und ich bin ja auch darauf eingegangen. Die Frage ist: muss das so bleiben, wenn die "anderen Daten" keinen brauchbaren Graphen ergeben?

**Comment by snaptec** [comment]
GGf. könnte man mit der Visualisierung herumspielen.
Am besten im Forum eine Umfrage starten ob Nachfrage vorhanden ist.

**Comment by snaptec** [comment]
Problem mit DC seitigem Speicher gelöst
