### ISSUE TITLE
bring back "interactive graphs"

### ISSUE THREAD

**Issue by tpd-opitz** [snaptec/openWB#422]
betrifft: Ver 1.7.302Nightly FireFox, Linux (Ubuntu)

In Version 1.6 waren die Darstellungen im Logging "interactive", man konnte also einen Breicht der Darstellung durch auswählen mit der Mouse zoomen und bekam (auch ohne zoom) an der Mausposition ein Fadenkreuz angezeigt, mit dem man die genaue Urzeit der Mouse-Position sowie die beiden dazugehörigen Skalenwerte angezeigt bekam. 

Bitte diese Funktionalität wieder aktivieren.

**Comment by snaptec** [comment]
Die Graph Engine wurde geändert, da die alte doch zu imperformant war/ist.
Ob / wie gut das bei der neuen klappen gilt es zu testen, hat aktuell aber keine Priorität.

**Comment by snaptec** [comment]
Zoom / Pan ist wieder implementiert in der Nightly
