### ISSUE TITLE
70% PV ist geil, aber...

### ISSUE THREAD

**Issue by theHolgi** [snaptec/openWB#469]
Hey, das habe ich auch gerade so gut wie implementiert, da poppt es im Hauptrepo auf... 😄 
Aber die Regelstrategie sollte angepaßt werden.

IST: Damit der Regler funktioniert, muss die Schwelle auf (MAX - 1400W) gesetzt werden, bei 10kW Peak also z.B. 5600W. Mehr als 7kW Einspeisung wird nicht (lange) passieren, dann ist die Anlage schon in der Abregelung.
Bei > 7kW beginnt die Ladung, versucht danach aber eine Einspeisung von 5600W zu behalten. Lädt also viel mehr als im Szenario (Corona, Auto fast voll, will nur keine Sonne verschwenden) notwendig ist.

SOLL:
Konfiguriert wird die maximale Einspeisung (d.h. 7000W resp. knapp darunter).
Dieser Wert wird angestrebt, darf aber _nicht überschritten werden_. d.h.: 
- Starten der Ladung bzw. Erhöhung des Stroms **sobald die Schwelle überschritten wird**
- Verringern der Ladung bzw. Abschalten, wenn die erwartete Einspeisung dann unterhalb der Schwelle ist.
(Verringern: Einspeisung < Schwelle-230W*Phasen; Abschalten: Einspeisung < Schwelle-6A*230V*Phasen)

Ich schicke gerne einen PR dazu. In ein paar Tagen.

**Comment by snaptec** [comment]
Ist das nicht das selbe wie jetzt nur das der mindestüberschuss auf 0 gesetzt ist? abschaltüberschuss muss ja bleiben, sonst macht er als hin und her

**Comment by theHolgi** [comment]
Ja, das wäre wohl dasselbe - nur daß ich Mindestüberschuss ja für die "nur PV" - Ladung sinnvollerweise hoch setze (bloß nicht Strom kaufen) und mit dem 70% Laden (immer) außer Kraft setzen will.
Den Mindestüberschuss mit 0 zu überschreiben, wäre wohl die einfachste Implementierung.

**Comment by snaptec** [comment]
Einzig die Berechnung des Abschaltüberschusses wirft bei mir noch fragen auf.
Sollte die nicht unterhalb der neuen Regelgrenze liegen?

**Comment by theHolgi** [comment]
Die Abschaltung erfolgt mit dem Ausdruck:
`if wattbezugint > abschaltuberschuss`
Durch die Verschiebung des Nullpunktes arbeiten wir um 0 herum, in Richtung (virtuellem) Netzbezug (`wattbezugint` mit positiven Werten).
Wir können also dann abschalten (ohne die Schwelle sofort zu überschreiten), wenn der "Netzbezug" bei 6A*230V*Phasen liegt.

**Comment by theHolgi** [comment]
Eliminierung eines der beiden Werte, "uberschuss" und "wattbezugint" wäre mir der Übersicht halber nicht ungelegen. Soll ich dazu auch mal einen PR machen?

**Comment by snaptec** [comment]
argh, du verschiebst ja Wattbezugint mit, ich hatte "nur" Überschuss verschoben.
Ja bitte

**Comment by theHolgi** [comment]
Nee, waren beide schon immer verschoben.
Eliminierung eines der beiden Werte machen wir aber nicht als Teil dieses PR, das würde ich dann neu im Master machen
