### ISSUE TITLE
Debuglog sendet Passwörter

### ISSUE THREAD

**Issue by benderl** [snaptec/openWB#480]
Entgegen der Angabe bei den Debugeinstellungen werden im Log zahlreiche Benutzernamen und Passwörter von verschiedenen Modulen mit aufgenommen. Das Skript senddebug.sh sollte dringend überarbeitet werden!
https://github.com/snaptec/openWB/blob/057b9ae49eec0029e28f129e7c47e067c329c2fc/runs/senddebug.sh#L28

**Comment by snaptec** [comment]
Wurde im Zuge neuer Variablen nicht mit angepasst, ist gefixt -> https://github.com/snaptec/openWB/commit/6bdbd0948681f2bc2b764647f30566d5183de489
