### ISSUE TITLE
Graph: Hausverbrauch fehlt in "Logging":"Daily"

### ISSUE THREAD

**Issue by S3phe** [snaptec/openWB#511]
Beim Klick auf "Logging" ("Live"-Ansicht) ist der Graph für den Hausverbrauch sichtbar.

Wenn man nun auf "Daily" umschaltet, taucht der Hausverbrauch in der Legende auf, jedoch nicht im Graph. 

-> Unter Monthly ist der Hausverbrauch wieder sichtbar. Somit sind die Daten definitiv vorhanden.

(OpenWB 1.7.010 Stable mit Tesla Gateway als EVU und PV-Modul)
![Bildschirmfoto 2020-05-10 um 16 21 50](https://user-images.githubusercontent.com/15612173/81501813-9cd5bb00-92da-11ea-950f-d64a5c992e6c.png)
![Bildschirmfoto 2020-05-10 um 16 22 44](https://user-images.githubusercontent.com/15612173/81501820-a7905000-92da-11ea-8f73-21d37741a64b.png)

**Comment by snaptec** [comment]
Welche Version?

**Comment by S3phe** [comment]
(OpenWB 1.7.010 Stable mit Tesla Gateway als EVU und PV-Modul)

**Comment by snaptec** [comment]
Dann ist das bereits gefixt.
Neue Beta kommt auch bald.
