### ISSUE TITLE
modules/bezug_fronius_sm/ mehrere WR berücksichtigen

### ISSUE THREAD

**Issue by Moosbueffel** [snaptec/openWB#550]
Beim Fronius können auch mehrere Wechselrichter im Betrieb sein z.B. bei Ost und West-Ausrichtung.

Abfrage deshalb nicht auf Device=0, sondern auf System. Da sind dann ggf. alle Devices vorhanden.

**Comment by snaptec** [comment]
Beim Fronius Bezug Modul wird der erste Wechselrichter abgefragt da hier das SmartMeter angeschlossen ist.
Beim Fronius PV Modul wird System abgefragt und alle angeschlossenen Wechselrichter berücksichtigt in wr_fronius:
/solar_api/v1/GetPowerFlowRealtimeData.fcgi?Scope=System

**Comment by Moosbueffel** [comment]
Ok, dann habe ich da wohl was übersehen.
