### ISSUE TITLE
Min+PV Laden startet nicht wenn in der Speicherbeachtung ein positiver Wert konfiguriert ist, im System aber kein Speicher angelegt wurde.

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#554]
Leider weicht die Beschreibung in den Einstellungen vom tatsächlichen Verhalten ab.

In den Einstellungen steht:
- Diese Funktionen sind nur aktiv, wenn ein Speicher konfiguriert wurde.

![grafik](https://user-images.githubusercontent.com/53753460/85015409-3610b080-b168-11ea-9a25-26f7ca5c2a64.png)

Dennoch startet das Laden Min+PV nur wenn beide Werte auf 0 gesellt sind obwohl kein Speicher konfiguriert ist. Gleichzeitig ist es auch noch so das am einzigen vorhandenen Ladepunkt SOC deaktiviert ist (hyundai ioniq hab leider keine möglichkeit den SOC zu ermitteln)

Allgemein würde ich erwarten das Dinge, die keinen Einfluss haben, wahlweise nicht angezeigt werden oder inaktiv sind. Die Settings "erschlagen" einen leider wenn man sich initial mit openWB befasst...

**Comment by snaptec** [comment]
Bin ich bei dir.
Erstmal, problem sollte gefixt sein - bitte in 1.8.005 prüfen.
Ausblendung steht noch auf der Agenda.
Ist stellenweise schon erfolgt, aber noch nicht 100% abgeschlossen

**Comment by JanFellner** [comment]
I give it a try :)

**Comment by JanFellner** [comment]
geht mit der 1.8.005 nightly kann zu.
Muss aber gleich noch eins aufreißen - Probleme und Verbesserungen für das Thema pushover .)
