### ISSUE TITLE
Konfiguration von PushOver

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#556]
Habe Verständnisprobleme und damit vermutlich Verbesserungspotential für das Thema PushOver.

Habe die App gekauft, finde in der App ein dort so genannten "User key"
Diesen habe ich mangels wissens unter "User String:" eingetragen

Leider initial versehentlich unter dem App Token da die kontextuelle Beschreibung in dem UI Framework unter dem Edit Control liegt und damit (für mich) leicht verwirrend platziert. (Es würde Abstand zwischen Optionen und kontextueller Beschreibung fehlen um die Zugehörigkeit von Text zu Option klarer herauszustellen (persönliche Meinung))

![grafik](https://user-images.githubusercontent.com/53753460/85017095-378fa800-b16b-11ea-902d-484cc66a893d.png)

Die Beschreibungstexte bringen hier imho keine verbsserung oder Klarheit da dass, was einzugeben ist ja schon ausreichend beschrieben wird.

Den App Token konnte ich nur durch auschecken der Sourcen in openwb.conf wieder finden.

- Der App Token sollte doch spezifisch sein für openwb. Warum sollte der Nutzer diesen editieren/ändern können? (Sollte man diese Option nicht ganz entfernen)
- Der User String sollte wie in der App und bei PushOver genannt User key heißen
- Ich vermisse einen Test Button. (Hab ich ehrlich gesagt auch in der Modul Konfig bei den ganzen 3. Systemen vermisst)

Habe die Funktion daher durch manuelles stoppen über die WebUI und reaktivieren des Ladens versucht zu triggern. Leider erfolglos. In den Logs finde ich hierzu nichts.
Wie kann ich das Problem am einfachsten diagnostizieren :)

**Comment by snaptec** [comment]
> Der App Token sollte doch spezifisch sein für openwb. Warum sollte der Nutzer diesen editieren/ändern können? (Sollte man diese Option nicht ganz entfernen)
Der App Token ist der Token den der User in seiner Pushover APP erstellt.

**Comment by JanFellner** [comment]
Schäm: Wer lesen kann ist klar im Vorteil 🤦 

Dennoch bekomme ich es nicht ans Laufen. In der WebUI von pushover kann ich mir als die eingerichtete APP eine Benachrichtigung schicken, diese wird auch zugestellt.

Auto ist leider voll, kann aktuell also nur anstecken abstecken als Push zustellen, was aber nicht gemeldet wird. In der WebUI verschwindet bzw. erscheint der Stecker beim abstecken anstecken.
Rebootet habe ich openWB ebenfalls bereits.

Gibts ein Log in openwb für die pushover Aktivitäten?

**Comment by JanFellner** [comment]
Ich schließe das Ticket. Ein test button für die Einrichtung wäre Wünschenswert.
