### ISSUE TITLE
Lademenge auslesen goe Charger

### ISSUE THREAD

**Issue by kaeferfreund** [snaptec/openWB#558]
Hi zusammen,

mir ist aufgefallen, dass die geladene Energie nur in kWh angezeigt wird, in der goe API wird das ganze zumindest für die aktuelle Ladung in Ws angegeben, also deutlich genauer.

Ich würde die Auslesefunktion mal anpassen und als PR Submitten, wenn es keine Bedenken gibt? @snaptec

**Comment by snaptec** [comment]
Das Problem ist das die Lademenge als Zählerstand funktioniert.
Die Lademenge je Ladevorgang würde das Logging komplett unbrauchbar machen.
