### ISSUE TITLE
Lademenge im Ladelog bei PV Ladung

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#561]
Das Ladelog ist aktuell in Verbindung mit PV bzw. Überschuss Laden leider wenig aussagekräftig. Mich interessieren weniger die kwh der einzelnen, zum Teil kurzen Ladevorgänge, als vielmehr wieviel ist heute bzw. seit dem letzten anstecken ins Fahrzeug geladen worden. 

Ebenso würde mich dies in der Status Übersicht interessieren.

Ohne Kenntnis der Datenbank in der es abgelegt wird eine Idee zur Umsetzung. 

Bei jedem Ansteckvorgang eines Fahrzeuges gibt es einen inkrementellen Zähler. Dieser Zähler erhöht sich also nur durch ab und anstecken. Die Ladevorgänge werden zusammen mit dem Zähler in die Datenbank geschrieben und bei der Anzeige des Ladelogs kombiniert. Lediglich ein Tageswechsel führt zu getrennten ansichten im Log. 

Andere Werte im Ladelog wie durchschnittliche Ladeleistung wären in diesem Zusammenhang irrelevant.

Jan

**Comment by snaptec** [comment]
Das Ladelog basiert tatsächlich auf einzelnen Ladungen. Es gibt einige die unterschiedliche Autos laden und z.B. zwischen nacht / PV Ladung unterscheiden wollen.
Ein Tages kWh je Ladepunkt ist per MQTT abfragbar und wird auf der Hauptseite angezeigt.
Hier gibt es "heute geladen"
