### ISSUE TITLE
E3DC  mit go-echarger und Tesla, Ladeleistung wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Sonnenstupsi** [snaptec/openWB#584]
![grafik](https://user-images.githubusercontent.com/68802777/88473063-1e240d80-cf1a-11ea-9d42-aecdf279d941.png)

Seit einigen Tagen wird die Ladeleistung nicht mehr angezeigt, obwohl der Tesla hier zB mit 6A lädt. Die Überschussladung (PV-Laden)  funktioniert damit auch nicht. Es wird immer mit dem am go-echarger eingestellten A-Wert geladen.
Auch das Umschalten von PV-Laden auf Stop wird komplett ignoriert.
Zunächst konnte ich den einwandfreien Betrieb durch ein System-Reboot wiederherstellen aber das funktioniert jetzt auch nicht mehr!
OpenWB-Version Stable: 1.8.000StableRC

**Comment by snaptec** [comment]
Vermutlich hat sich die go-e IP geändert oder der go-e ist nicht mehr im WLAN

**Comment by Sonnenstupsi** [comment]
Ja, da wäre ich nicht drauf gekommen, die IP Adresse vom Go echarger hatte sich geändert. Danke für den Tipp!Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: snaptec <notifications@github.com> 
Datum: 27.07.2020  10:06  (GMT+01:00) 
An: snaptec/openWB <openWB@noreply.github.com> 
Cc: Sonnenstupsi <alf.reinhard@t-online.de>, Author <author@noreply.github.com> 
Betreff: Re: [snaptec/openWB] E3DC  mit go-echarger und Tesla, Ladeleistung wird nicht mehr angezeigt (#584) 


Vermutlich hat sich die go-e IP geändert oder der go-e ist nicht mehr im WLAN
