### ISSUE TITLE
Audi SOC Modul geht nicht mehr

### ISSUE THREAD

**Issue by EyeOfTheStorm** [snaptec/openWB#599]
Audi hat scheinbar die API vor ein paar Tagen geändert. Kann sich das mal jemand ansehen?

**Comment by andig** [comment]
Siehe https://github.com/davidgiga1993/AudiAPI/issues/13

**Comment by andig** [comment]
Es braucht mal ein Call Trace der App. Im Ticket steht wie das geht- ich habe leider kein Android...

**Comment by premultiply** [comment]
Gibts die App nicht als APK welches man einfach entpacken kann und dann den Quelltext ansehen kann?
Das ist doch meist ohnehin so ein zusammengeschusterter Web-Javascript-Java-Baukasten-Kram

Normalerweise geht das bei Android-Apps

**Comment by andig** [comment]
Genau, steht alles unter dem Link. Ich hab kein Android...

**Comment by premultiply** [comment]
Ich auch nicht. Braucht man aber auch nicht. Dafür gibt es Internetdienste denen man das runtergeladene APK einwirft und dann den entpackten Salat bekommt.

**Comment by stilicrafter** [comment]
Google stellt doch einen android emulator zur Verfügung.

**Comment by andig** [comment]
Das Problem ist lange gelöst, Issue kann geshclossen werden.

**Comment by andig** [comment]
Was ist an diesem Kommentar off-topic in Anbetracht von https://github.com/snaptec/openWB/commit/79a1563ee2913382d4dcf12315d224f5f54f822f?
