### ISSUE TITLE
SoC-Auslesung für BMW i3

### ISSUE THREAD

**Issue by iot4all** [snaptec/openWB#6]
Implementierung der SoC-Auslesung (BMW i3) über die API des "connected drive"-Prortals mit den Hinweisen dieses links:
https://github.com/jupe76/bmwcdapi

**Comment by snaptec** [comment]
Update für alle:
Beta Version läuft bei iot4all

wenn das zuverlässig funktioniert -> in den nächsten releases dabei

**Comment by iot4all** [comment]
Du Kevin,

ich teste gerade Nachtladen mit 70% SoC. Im Fenster "Nacht SOC Freitag bis
Sonntag" bei LP1 wird der Vorgabewert nicht gespeichert. Ist nach SAVE bei
Kontrolle immer wieder leer. Kannst Du das beim nächten update mit fixen?
Bei "Nacht SOC Sonntag bis Donnerstag" klappt es im LP1

Bei LP2 klappen die beiden SoC, dafür wird "Nachtladen Uhrzeit ab" nicht
übernommen.

Ansonsten sind die Optionen bei Nachtladen gelinde gesagt VORBILDLICH :-).
Wenn wird nur die SoC-Vorgabe noch bei Sofort Laden reinbekommen, wie
besprochen, wäre das 1A.

Zum Glück ist erst Dienstag und der erste SoC-Wert wird bei LP1
gespeichert. Mal sehen, ob der i3 morgen 70% hat.

In den Stop-button würde ich noch ein Sternchen hinzufügen und darunter
*...ggf. Nachtladen
schreiben.

Viele Grüße
Frank

snaptec <notifications@github.com> schrieb am Mo., 30. Juli 2018, 21:39:

**Comment by iot4all** [comment]
Und am LP2 wird zwar die Nachtladestromstärke auf der Config eingestellt
und gespeichert, aber nicht auf die Hauptseite übernommen. Dort stehen bei
LP2 immer 12A fix.

Good night

F. S. <mailing3000@googlemail.com> schrieb am Di., 31. Juli 2018, 23:02:

**Comment by iot4all** [comment]
Ok - er macht erstmal seine Nachtladung.

Nun ist das einzig unschöne, dass man nicht mehr von der Hauptseite aus
Stoppen kann.

Idee:
Den Stop-button teilen in
"Stop+ggf. NL" sowie "Notstop"
oder
"Nachtladen" sowie "Stop"?

Hast Du ev. eine bessere Idee, um manuell auch bei NL stoppen zu können?

VG

F. S. <mailing3000@googlemail.com> schrieb am Di., 31. Juli 2018, 23:24:

**Comment by snaptec** [comment]
Ist implementiert
