### ISSUE TITLE
OpenWB lädt ohne Ladefreigabe -> ich kann aktuell faktisch nur das Auto abstecken

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#625]
Leider vermisse ich in der WebUI immer noch eine Möglichkeit zu diagnostizieren warum openWB macht was es macht.

Ohne jegliche Eingriffe (Confi/Firmware) hat OpenWB gestern einfach weiter geladen obwohl keiner der dafür nötigen Faktoren erfüllt war.

- PV hat nichts mehr geliefert.
- Speicher wurde entladen.
- Die Abschaltverzögerung war komplett überschritten.

Ich habe auf Stop gestellt -> Lädt weiter. Ich habe also das Auto abgesteckt.

Heute früh neuer Versuch. Selbes Verhalten. Obwohl keiner der Faktoren ein Laden erlauben dürfte wird angefangen zu Laden.

LadeController ist ein EVSE-Wifi Version 1.02 konfiguriert auf Remote Controlled.
(Update habe ich gemacht als die Version rauskam, also irgendwann im August)
Im Register 1000 steht 6 obwohl openWB auf STOP steht.

Wie kann ich sowas als Nutzer irgendwie diganostizieren?
Hatte jetzt alle möglichen Versionen drauf:
Stable: 1.8.000StableRC (aktuell drauf)
Beta: 1.8.400Beta 
Nightly: 1.8.406Nightly

**Comment by JanFellner** [comment]
Vom Raspi (virtualisiert auf ESXI) komme ich zum EVSE.
Was passiert wenn openwb den LadeController temporär mal nicht erreichen kann (hängt ja im WLAN).
Wird das nochmals versucht?

-> insgesamt fehlt mir irgendwie ein technisches Log um bei Problemen zunächst mal selbst schauen zu können.
Gibt es sowas wenn ja wie kommt man dorthin? In der WebUI finde ich nichts um das Log abzugreifen.

![grafik](https://user-images.githubusercontent.com/53753460/94904128-1e510400-049b-11eb-8752-8aeaf925f2e8.png)

**Comment by snaptec** [comment]
das Log ist unter /var/www/html/openWB/ramdisk/openWB.log zu finden
Das sollte hier auch Aufschluss geben.

**Comment by drego83** [comment]
und wie komme ich an die log ran, wenn ich eine fertige openWB gekauft habe? Ich habe keinen Zugriff auf die log ausgehend von der Webseite ...

**Comment by snaptec** [comment]
Das geht auch aus dem Browser aufrufen @drego83

**Comment by drego83** [comment]
Kannst Du mir bitte verraten wo und wie? Danke

**Comment by snaptec** [comment]
http://ipderopenWB/openWB/ramdisk/openWB.log

**Comment by Der-Kieler** [comment]
Es wäre toll, wenn das log (und vielleicht wesentliche weitere) über die Oberfläche erreichbar wären.
Würde viele Fragen vermeiden.

**Comment by JanFellner** [comment]
Sehe ich aktuell genauso.

Speziell wünschen würde ich mir hierbei eine Seite in der ich die letzten 10/20/50 Log Einträge einsehen kann da das Öffnen der Datei ohne Console aktuell praktisch nicht nutzbar ist. Muss im Browser immer erst ganz nach unten Scrollen.
Die Ansicht könnte optional live laufen, sprich immer die letzten X Einträge anzeigen.

Weiterhin eine Seite in der ich immer live die letzte Berechnung sehe.

**Comment by snaptec** [comment]
Unter Status ist das Debug Log nun auch sichtbar
