### ISSUE TITLE
fehlende Initialisierung in der Ramdisk

### ISSUE THREAD

**Issue by benderl** [snaptec/openWB#668]
https://github.com/snaptec/openWB/blob/1fdda0a1fb34853d4f1a1942110c071e4c1a2c8c/loadvars.sh#L1580
https://github.com/snaptec/openWB/blob/1fdda0a1fb34853d4f1a1942110c071e4c1a2c8c/loadvars.sh#L1581
Die Dateien existieren noch nicht in der Ramdisk. Eine Anpassung der atreboot.sh ist notwendig.

**Comment by snaptec** [comment]
Ist hier:
https://github.com/snaptec/openWB/commit/611b5f431bac8b0485314b02a3dea31bfb0e3bf8
bereits erfolgt.
