### ISSUE TITLE
bootmodus nach erster Installation nicht definiert

### ISSUE THREAD

**Issue by benderl** [snaptec/openWB#669]
https://github.com/snaptec/openWB/blob/1fdda0a1fb34853d4f1a1942110c071e4c1a2c8c/runs/atreboot.sh#L2926
https://github.com/snaptec/openWB/blob/1fdda0a1fb34853d4f1a1942110c071e4c1a2c8c/runs/atreboot.sh#L2927
In der openwb.conf im Git fehlt der Eintrag "bootmodus". Der wird zwar nachgetragen, jedoch ist die Variable an den Stellen noch leer, wenn an den Broker gesendet wird. Das könnte Ursache für die Abstürze der mqttsub.py bei eigenen Installationen sein.

**Comment by snaptec** [comment]
Sollte hiermit:
https://github.com/snaptec/openWB/commit/54f5163f1384559364f818ee0788e821dbd19926

erledigt sein.
