### ISSUE TITLE
Negative Werte bei geladenen kW/km

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#673]
Feststellung: Stellt man beim sofort laden einen bestimmten kw/h Wert ein der geladen werden soll und wechselt anschließend (ohne das dieser Wert jemals erreicht wurde) in einen anderen Lade Modus stehen in der Übersicht negative Ladewerte.
Erwartung: Wechsle ich den Lademodus werden diese negativen Werte zurück gesetzt und der Zähler beginnt von 0
![Screenshot_20201031-100926_Firefox](https://user-images.githubusercontent.com/53753460/97775527-ae996c00-1b61-11eb-8b6c-bd32c117617e.jpg)

**Comment by snaptec** [comment]
Um was für einen Ladepunkt handelt es sich?

**Comment by JanFellner** [comment]
SimpleEVSEWifi mit aktuellster Firmware
Current Firmware Version: 1.0.2

OpenWb läuft mit
installierte Version: 1.8.412Nightly (2020-10-19 08:39:47 +0200 [104333f0] )

**Comment by JanFellner** [comment]
Hab das Problem leider immer noch, praktisch jedes Mal wenn ich die openwb Webseite aufrufe. Neuste Version is.  @``

**Comment by JanFellner** [comment]
Any news on this one? I still face it so I can never tell how much I charged after the charging has completed... 😔

**Comment by benderl** [comment]
@JanFellner kannst Du bitte die genauen Schritte aufführen, um das Verhalten nachstellen zu können? Sind danach auch im Ladelog Einträge mit negativen Werten vorhanden?

**Comment by JanFellner** [comment]
@benderl naja, ich stecke das Auto an :). Ich schaue in die Weboberfläche und sehe negative Werte.
Um sagen zu können wie es Auftritt müsste ich zunächst verstehen wann dieser Wert denn überhaupt gelöscht wird.

![image](https://user-images.githubusercontent.com/53753460/107118891-27f0db00-6884-11eb-9394-187cb42c70ac.png)

Heute früh beim Laden standen wieder negative Werte drinn.
Im Ladelog sehe ich nichts auffälliges.

Gibt es denn mittlerweile eine irgendwie geartete From von Diagnosedaten welche man an ein solches Ticket anhängen könnte?

Jan

**Comment by JanFellner** [comment]
Heute erneut. Negative Werte in der UI.
Fragen meinerseits hierzu hatte ich ja schon geschrieben.

![Screenshot_20210218-110919_Firefox](https://user-images.githubusercontent.com/53753460/108341469-f5c36f80-71d9-11eb-9b0e-7baf36972a32.jpg)
![Screenshot_20210218-110934_Firefox](https://user-images.githubusercontent.com/53753460/108341471-f65c0600-71d9-11eb-90c4-b8b0fa40eacc.jpg)

**Comment by JanFellner** [comment]
Und wieder. Negative Werte... 
![Uploading Screenshot_20210219-130054_Firefox.jpg…]()

**Comment by JanFellner** [comment]
Bald habe ich Jahrestag... 
![Screenshot_20211009-140332_Firefox](https://user-images.githubusercontent.com/53753460/136657123-0aae7c39-4438-465b-b720-972395dd9594.jpg)

Daher nochmals die Frage: Wann wird der Zähler zurückgesetzt/initialisiert?

**Comment by JanFellner** [comment]
ich schließe dieses ticket da es auf rückfragen seitens der entwickler leider keinerlei feedback gibt.
