### ISSUE TITLE
Längenbegrenzung bei 1. Smart Home Gerät

### ISSUE THREAD

**Issue by JanFellner** [snaptec/openWB#674]
Der Name des 1. Smart home Gerätes scheint beim Speichern/Laden irgendwo verkürzt zu werden. Ich würde gerne Waschmaschi eintragen. Die Ui erlaubt dies. Ich ändere nur den Namen gehe unten auf Speichern, der Name wird nicht übernommen. 

![Screenshot_20201031-101912_Firefox](https://user-images.githubusercontent.com/53753460/97775636-9c6bfd80-1b62-11eb-9524-5bd7373fad63.jpg)

**Comment by snaptec** [comment]
Was steht im MQTT Log (unter Status einsehbar)?
Bis wieviele Zeichen geht?

**Comment by JanFellner** [comment]
![image](https://user-images.githubusercontent.com/53753460/97798041-b836d880-1c22-11eb-8926-89210bdd630b.png)

Im SmartHomeLog steht auch nur Waschm.

Egal was ich eintrage und speichere, es steht am Scluss wieder auf Waschm.

**Comment by JanFellner** [comment]
closed fixed?
closed cannot reproduce?
closed won´t fix?

**Comment by benderl** [comment]
Fixed: #760
