### ISSUE TITLE
Smarthome 2.0 Problem Tasmota ohne Leistungsmessung

### ISSUE THREAD

**Issue by StefanKi** [snaptec/openWB#675]
Ich habe eine Tasmota Steckdose ohne Leistungsmessung.
Diese funktioniert mit der Version 1.8.400Beta nicht.
Das Problem ist, dass bei mir (ich vermute, dass das wegen der fehlenden Leistungsmessung ist), der Status 8 keinen Inhalt außer Uhrzeit und Datum liefert:
`{"StatusSNS":{"Time":"2020-10-31T13:37:02"}}`

Ich habe den Code folgendermaßen adaptiert (ab Zeile 345):
`                   answer = json.loads(str(urllib.request.urlopen("http://"+config.get('smarthomedevices', 'device_ip_'+str(numberOfDevices))+"/cm?cmnd=Status", timeout=3).read().decode("utf-8")))
                    watt=0
                    if ( int(answer['Status']['Power']) > 0 ):
                        relais=1
                    else:
                        relais=0
`
Damit funktioniert es dann. (Ist natürlich nicht die fertige Lösung, aber der Test, dass es dann geht, weil ja sonst die Watt falsch sind)

**Comment by benderl** [comment]
Bitte nochmal mit dem überarbeiteten SmartHome 2.0 testen. Da hat sich seit Oktober viel verändert.

**Comment by benderl** [comment]
Anscheinend besteht kein weiteres Interesse.
