### ISSUE TITLE
Keine Graphen auf der Home page auf Rasbian Buster. Logging funktioniert.

### ISSUE THREAD

**Issue by JimKnopf1503** [snaptec/openWB#717]
Hi!
Auf einem frischen Buster system und Installation über "sh openwb-install.sh" werden die Graphen auf der Startseite nicht dargestellt. Nach Reboot kommt er Hinweis auf zu wenig Datenpunkte. Wenn die vollständig sind wird nichts dargestellt. Nur der Text: "Graph lädt, bitte warten". Dabei bleibt es auch nach Stunden.
Auf Stretch läuft es. Somit ist es so nicht auf einem Pi 4 lauffähig.

Gruß,
Burkhard

**Comment by benderl** [comment]
Es gibt mittlerweile einige Installationen, die auf Buster laufen. Bitte mit dem aktuellen Installationsskript und der Nightly 1.9.222 oder neuer testen.
