### ISSUE TITLE
Add Json parsing option for battery

### ISSUE THREAD

**Issue by tkoeberl** [snaptec/openWB#761]
It's possible for PV/EVU to use a json/jq, but not for the battery. Would be cool to have this.

**Comment by DetMoerk** [comment]
How many different values must be extracted? Only one?

Best Regards 
Det

**Comment by DetMoerk** [comment]
@benderl: Wenn ich das richtig sehe gibt es bei Batteriespeicher die Werte Speicherleistung und Speichersoc. 

Bedeutet 
1 URL und 2 Filter Bedingungen analog dem PV JSON Modul würden reichen oder?

Könnte ich mal angehen und in den Batterie Bereich einbauen.

VG
Det

**Comment by benderl** [comment]
Das wäre super! Speicher benötigen nur die aktuelle Leistung und den SoC.
Leistung in Watt -> ramdisk/speicherleistung
SoC ans Integer -> ramdisk/speichersoc

**Comment by DetMoerk** [comment]
@tkoeberl : I'm working on it. Can you send me a example json output from your battery?

Regards
Det

**Comment by tkoeberl** [comment]
@DetMoerk : sure:
`{"Apparent_output":90,"BackupBuffer":"0","BatteryCharging":false,"BatteryDischarging":false,"Consumption_Avg":337,"Consumption_W":409,"Fac":50.016502380371094,"FlowConsumptionBattery":false,"FlowConsumptionGrid":true,"FlowConsumptionProduction":true,"FlowGridBattery":false,"FlowProductionBattery":false,"FlowProductionGrid":false,"GridFeedIn_W":-333,"IsSystemInstalled":1,"OperatingMode":"2","Pac_total_W":-3,"Production_W":79,"RSOC":20,"RemainingCapacity_W":4528,"Sac1":90,"Sac2":null,"Sac3":null,"SystemStatus":"OnGrid","Timestamp":"2021-02-09 16:02:18","USOC":13,"Uac":228,"Ubat":186}`

**Comment by DetMoerk** [comment]
As the Battery Module only have two values to hold, I guess 
The values Consumption_W = Speicherleistung 
and 
RSOC =Speichersoc
.

I'll try to set it up as a module.

Regards
Det

**Comment by DetMoerk** [comment]
@tkoeberl: give it a test when the PR is merged.

# 1031

**Comment by DetMoerk** [comment]
@tkoeberl: if you need to invert the value of e.g. Consumption_W, wite the filter: .Consumption_W***-1**

**Comment by tkoeberl** [comment]
@DetMoerk : openwb still does not have a docker container installation?

**Comment by DetMoerk** [comment]
I guess not. I'm not in the core developer Team, I only added some modules around, which I also need. 

Did you test the speicher_json module?

Regards
Det

**Comment by benderl** [comment]
We have no plans to support a docker container right now. If you are familiar with docker and manage to set it up, you are welcome to share your modifications.

**Comment by tkoeberl** [comment]
I'm really sorry. I already destroyed my openwb installation. Thats why I was asking for the docker container.
