### ISSUE TITLE
Awattar nimmt deutsche statt österreichische Preise

### ISSUE THREAD

**Issue by riesi77** [snaptec/openWB#799]
Aktiviert man die Awattar Einstellung und wählt "Österreich" als Land aus, so werden trotzdem die Preise aus Deutschland angezeigt.
Version 1.9.003

**Comment by snaptec** [comment]
Genutzt wird die österreichische API. Die Angabe erfolgt netto. Daher ggf die Differenz?

**Comment by riesi77** [comment]
![image](https://user-images.githubusercontent.com/67387975/102369535-5953d580-3fbc-11eb-909d-61909239bd4c.png)

**Comment by riesi77** [comment]
![image](https://user-images.githubusercontent.com/67387975/102369704-8acca100-3fbc-11eb-871b-887fe1c10d0a.png)

**Comment by riesi77** [comment]
![image](https://user-images.githubusercontent.com/67387975/102369747-96b86300-3fbc-11eb-982d-f96a58a4d2b0.png)

**Comment by riesi77** [comment]
Ja, das scheint zu stimmen. Erst war ich verwirrt, aber die Grafik nimmt ja einen unterschiedlichen Zeitbereich. Und die Nettoangabe auf der Homepage war mir auch neu.
