### ISSUE TITLE
Dark Theme: Uncaught type error: client.conect ist not function

### ISSUE THREAD

**Issue by fawick** [snaptec/openWB#826]
There is a typo in the function call at https://github.com/snaptec/openWB/blob/a90d10ef4e698a339a72447ef53d5cb40dc6ffaf/web/themes/dark/setupMqttServices.js#L377: I guess, `conect` should be `connect`.

![image](https://user-images.githubusercontent.com/1886500/103226115-aa07ee80-492b-11eb-832c-b9730d207d3a.png)

**Comment by snaptec** [comment]
Thanks!
Fixed
https://github.com/snaptec/openWB/commit/6cc2ca384c877b3b3b936995e6b91ad90916b41d
