### ISSUE TITLE
EVU JSON Modul Bezug und Einspeisung in kWh oder Wh?

### ISSUE THREAD

**Issue by Chringbay** [snaptec/openWB#828]
Guten Abend,

zuerst einmal ein riesiges Lob an dieses Projekt! Echt super was ihr hier auf die Beine gestellt habt!

Ich habe auf einem Raspberry Pi 4 ein OpenWB Stand-Alone laufen. Ladepunkt und E-Auto habe ich noch keines. Solaranlage mit SMA Wechselrichter ist vorhanden (Werte werden problemlos per ModbusTCP abgefragt). Den Stromzähler lese ich mit einem IR-Lesekopf aus und verarbeite die Daten mit dem Smart-Meter-Modul in IObroker. Dort habe ich die Werte für den aktuellen Bezug in Watt, die Zählerstände für Bezug und Einspeisung in kWh.

Diese frage ich über die REST-API als JSON im EVU Modul ab (mit den entsprechenden jq Kommandos). Für den Hausverbrauch klappt es auch problemlos. Bei den Werten für Bezug und Einspeisung liege ich aber um den Faktor 1000 daneben (sichtbar unter Status - Bild unten). Kann es sein, dass die Beschreibung im Modul nicht stimmt und für Bezug und Einspeisung die Werte ebenfalls in Watt anzugeben sind? Oder verstehe ich es falsch und der "." ist das 1000er Trennzeichen? 

![image](https://user-images.githubusercontent.com/73064022/103240188-e4838280-494f-11eb-8929-8dab2c862fb7.png)

**Comment by snaptec** [comment]
Die Werte sind als integer in Wh anzugeben. 

Das ui zeigt dann kWh an.
