### ISSUE TITLE
Fix SOC Leaf ZE0

### ISSUE THREAD

**Issue by demmelme** [snaptec/openWB#832]
Das aktuelle (Version 1.9) SOC-Modul für den Nissan Leaf funktioniert bei mir nicht. Ich habe einen Fix, mit dem es funktioniert

**Comment by benderl** [comment]
Sagst Du uns auch, was Du geändert hast?

**Comment by demmelme** [comment]
Gerne. Bin zum ersten Mal auf github unterwegs und dachte ein Issue wäre ein guter Anfang ;-). Inzwischen habe ich einen entsprechenden PullRequest erstellt zum Review erstellt.
