### ISSUE TITLE
Graph in der Übersicht nicht gleichmäßig

### ISSUE THREAD

**Issue by Canonip** [snaptec/openWB#887]
In der Übersicht sind die Bezeichnungen der zeitlichen Abstände auf der X-Achse nicht gleichmäßig.
z.B. 11:44 - 11:53 (9 Minuten) und danach 11:54 (1 Minute)

![image](https://user-images.githubusercontent.com/20642490/104444427-0f98e380-5598-11eb-8c9c-4c67c1e2eee4.png)

Einstellungen:

- 30 Minuten Zeitintervall im Graph
- Standard Theme
- PV+EVU+Speicher eingebunden (Kostal Plenticore)
- OpenWB Version 1.9.009 (2021-01-08 12:33:35 +0100 [0bf3001c] ) auf OpenWB series2

**Comment by snaptec** [comment]
War der Browser Tab stellenweise im Hintergrund?
Passt es nach einem Reload der Seite?

**Comment by Canonip** [comment]
Ausprobiert mit Chrome 87, Edge 87, Firefox 84 auf Windows 10 1909
Neustart der Browser hat nicht geholfen
Reboot (und 30 min warten) der openWB hat nicht geholfen.

Ich wechsle gleich von Nightly 1.9.009 zu Stable 1.9.003 und schaue ob es auch hier der Fall ist

**Comment by Canonip** [comment]
Bei 1.9.003 das gleiche:
![image](https://user-images.githubusercontent.com/20642490/104463712-68757580-55b2-11eb-9e6e-e69a03de47a1.png)

**Comment by cshagen** [comment]
Es handelt sich um einen Fehler in graphing.sh.
Die Zeilen 50-99 in all-live.graph auf der Ramdisk werden nicht per MQTT publiziert. 
Ich habe das bei mir lokal korrigiert und es funktioniert. Kann einen Pull-Request einstellen, falls gewünscht.

**Comment by benderl** [comment]
@cshagen ja, bitte mach das.

**Comment by benderl** [comment]
Sollte mit #983 behoben sein.
