### ISSUE TITLE
Keine Code Eingabe auf Display in Nightly

### ISSUE THREAD

**Issue by DetMoerk** [snaptec/openWB#889]
Hallo zusammen,

in der Nightly ist auf dem Display der Standard+ keine Eingabe für den Code mehr vorhanden . Es gibt jetzt einen Punkt Status, aber die Code Eingabe finde ich nicht mehr.

VG
Det

**Comment by DetMoerk** [comment]
![20210113_205936.jpg](https://user-images.githubusercontent.com/76627235/104504576-f23d3700-55e2-11eb-8ca8-6cce7a2780e2.jpg)

![20210113_210126.jpg](https://user-images.githubusercontent.com/76627235/104504594-fa957200-55e2-11eb-8654-9e6b641d9b00.jpg)

**Comment by benderl** [comment]
Da das quasi ein manueller Rfid ist, wird der Punkt nur noch angezeigt, wenn auch Rfid im Modus 1 oder 2 aktiviert ist.

**Comment by DetMoerk** [comment]
Jetzt muss ich dann doch mal fragen, ob sowas irgendwo dokumentiert ist.

VG
Det

**Comment by benderl** [comment]
https://github.com/snaptec/openWB/commit/4efac89f924ca8c2a98f254a88ec0f9ef20cda15
