### ISSUE TITLE
Livechart mit 3 Verbrauchern

### ISSUE THREAD

**Issue by chillichilli** [snaptec/openWB#945]
Wäre es möglich, anstelle von heute 2 Verbrauchern zukünftig auch 3 Verbraucher in den Livecharts anzuzeigen? 
Ich würde das gerne nutzen, um mir für alle 3 Phasen im Haus deren aktuelle Belastung/Watt im Livechart anzeigen zu lassen.
So kann ich genauer sehen, was gerade im Haus passiert.
Vom Code her müsste da dann wohl im web code (live.js, livechart_chart.js, livechart.js, processAllMqttMsgs, values.php) und im runs/pubmqtt.sh und cron5min.sh das mit aufgenommen werden.
Ich könnte auch gerne einen patch zur Verfügung stellen.
Vielen Dank schonmal !

**Comment by snaptec** [comment]
Smarthome2.0 bzw dort http nutzen. 

Die Verbraucher werden künftig nicht mehr unterstützt bzw eben von smarthome 2 abgelöst. Daher kommt da auch kein Dritter.
