### ISSUE TITLE
SOC vom Hyundai Ioniq per bluetooth auslesen

### ISSUE THREAD

**Issue by chillichilli** [snaptec/openWB#946]
Ich würde gerne folgendes SoC Modul für den Hyndai Ioniq (28kWh / vor-Facelift) beisteuern und aufnehmen lassen.
Man kann über Bluetooth vom Raspberry Pi mit einem OBD2 Bluetooth Dongle (ELM327) im Hyndai Ioniq kommunizieren und solange der Ladevorgang läuft auf 0.5% genau den Ladestand auslesen.

modules/soc_ioniq:
[soc.sh.txt](https://github.com/snaptec/openWB/files/5862881/soc.sh.txt)
[readobd2.py.txt](https://github.com/snaptec/openWB/files/5862882/readobd2.py.txt)
[main.sh.txt](https://github.com/snaptec/openWB/files/5862884/main.sh.txt)

ELM327.py and PiOBD2Hat.py in soc_ioniq/dongles Verzeichnis
[ELM327.py.txt](https://github.com/snaptec/openWB/files/5862887/ELM327.py.txt)
[PiOBD2Hat.py.txt](https://github.com/snaptec/openWB/files/5862888/PiOBD2Hat.py.txt)

car.py, IONIQ_BEV.py sowie für Kona und eNiro die Dateien in soc_ioniq/cars
[IONIQ_BEV.py.txt](https://github.com/snaptec/openWB/files/5862889/IONIQ_BEV.py.txt)
[KONA_EV.py.txt](https://github.com/snaptec/openWB/files/5862890/KONA_EV.py.txt)
[car.py.txt](https://github.com/snaptec/openWB/files/5862891/car.py.txt)
[NIRO_EV.py.txt](https://github.com/snaptec/openWB/files/5862892/NIRO_EV.py.txt)

Würde mich freuen, wenn diese Module noch mit aufgenommen werden würden. 
Die OBD2 Adresse des Bluetoogh Dongle im Auto müsste noch einstellbar gemacht werden.
Diese kann man per "sudo bluetoothctl" und dann "scan on" während eines Ladevorgangs in der Nähe vom Auto/Bluetooth Adapter herausgefunden werden.

Die Grundlage des Codes stammt von evnotify. Dort waren auch Module für den Hyundai Kona und den e-Niro enthalten. Ich habe den Code dann für openWB angepasst.

**Comment by benderl** [comment]
Bluetooth ist bei den fertigen openWB deaktiviert, da wir den belegten seriellen Port benötigen. Daher wird es keine offizielle Entwicklung hierzu geben. Wenn ein entsprechendes Modul von der Community entwickelt wird, können wir das sicher integrieren.
