### ISSUE TITLE
Tesla SOC funktioniert nicht

### ISSUE THREAD

**Issue by elha** [snaptec/openWB#989]
Tesla hat seinen Auth-Mechanismus umgestellt. 
Auf
https://tesla-api.timdorr.com/api-basics/authentication
ist der neue Ablauf dokumentiert.

**Comment by elha** [comment]
Ich hab einen quick-fix gebaut:
https://github.com/elha/openWB/commit/7cca061abf7c0023d5d6a41a0638ded50021aa9f

Ich bin leider kein Python-Crack. Der code ist daher sicher grausig, ich hab daher keinen Pullrequest gemacht.
Login-Code von https://github.com/enode-engineering/tesla-oauth2

**Comment by benderl** [comment]
Wir benötigen noch den Refresh der Token, da das Kennwort nach Erhalt der Token von openWB entfernt wird. Dazu gab es gerade neue Infos. Wir sind dran.
